// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Protocol.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_Protocol_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_Protocol_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "Enum.pb.h"
#include "Struct.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_Protocol_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_Protocol_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_Protocol_2eproto;
namespace Protocol {
class C_Move;
struct C_MoveDefaultTypeInternal;
extern C_MoveDefaultTypeInternal _C_Move_default_instance_;
class C_WaterBomb;
struct C_WaterBombDefaultTypeInternal;
extern C_WaterBombDefaultTypeInternal _C_WaterBomb_default_instance_;
class S_AddObject;
struct S_AddObjectDefaultTypeInternal;
extern S_AddObjectDefaultTypeInternal _S_AddObject_default_instance_;
class S_EnterGame;
struct S_EnterGameDefaultTypeInternal;
extern S_EnterGameDefaultTypeInternal _S_EnterGame_default_instance_;
class S_Move;
struct S_MoveDefaultTypeInternal;
extern S_MoveDefaultTypeInternal _S_Move_default_instance_;
class S_MyPlayer;
struct S_MyPlayerDefaultTypeInternal;
extern S_MyPlayerDefaultTypeInternal _S_MyPlayer_default_instance_;
class S_RemoveObject;
struct S_RemoveObjectDefaultTypeInternal;
extern S_RemoveObjectDefaultTypeInternal _S_RemoveObject_default_instance_;
class S_Tilemap;
struct S_TilemapDefaultTypeInternal;
extern S_TilemapDefaultTypeInternal _S_Tilemap_default_instance_;
}  // namespace Protocol
PROTOBUF_NAMESPACE_OPEN
template<> ::Protocol::C_Move* Arena::CreateMaybeMessage<::Protocol::C_Move>(Arena*);
template<> ::Protocol::C_WaterBomb* Arena::CreateMaybeMessage<::Protocol::C_WaterBomb>(Arena*);
template<> ::Protocol::S_AddObject* Arena::CreateMaybeMessage<::Protocol::S_AddObject>(Arena*);
template<> ::Protocol::S_EnterGame* Arena::CreateMaybeMessage<::Protocol::S_EnterGame>(Arena*);
template<> ::Protocol::S_Move* Arena::CreateMaybeMessage<::Protocol::S_Move>(Arena*);
template<> ::Protocol::S_MyPlayer* Arena::CreateMaybeMessage<::Protocol::S_MyPlayer>(Arena*);
template<> ::Protocol::S_RemoveObject* Arena::CreateMaybeMessage<::Protocol::S_RemoveObject>(Arena*);
template<> ::Protocol::S_Tilemap* Arena::CreateMaybeMessage<::Protocol::S_Tilemap>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace Protocol {

// ===================================================================

class S_EnterGame final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.S_EnterGame) */ {
 public:
  inline S_EnterGame() : S_EnterGame(nullptr) {}
  ~S_EnterGame() override;
  explicit PROTOBUF_CONSTEXPR S_EnterGame(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  S_EnterGame(const S_EnterGame& from);
  S_EnterGame(S_EnterGame&& from) noexcept
    : S_EnterGame() {
    *this = ::std::move(from);
  }

  inline S_EnterGame& operator=(const S_EnterGame& from) {
    CopyFrom(from);
    return *this;
  }
  inline S_EnterGame& operator=(S_EnterGame&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const S_EnterGame& default_instance() {
    return *internal_default_instance();
  }
  static inline const S_EnterGame* internal_default_instance() {
    return reinterpret_cast<const S_EnterGame*>(
               &_S_EnterGame_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(S_EnterGame& a, S_EnterGame& b) {
    a.Swap(&b);
  }
  inline void Swap(S_EnterGame* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(S_EnterGame* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  S_EnterGame* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<S_EnterGame>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const S_EnterGame& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const S_EnterGame& from) {
    S_EnterGame::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(S_EnterGame* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.S_EnterGame";
  }
  protected:
  explicit S_EnterGame(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kAccountIdFieldNumber = 2,
    kSuccessFieldNumber = 1,
  };
  // uint64 accountId = 2;
  void clear_accountid();
  uint64_t accountid() const;
  void set_accountid(uint64_t value);
  private:
  uint64_t _internal_accountid() const;
  void _internal_set_accountid(uint64_t value);
  public:

  // bool success = 1;
  void clear_success();
  bool success() const;
  void set_success(bool value);
  private:
  bool _internal_success() const;
  void _internal_set_success(bool value);
  public:

  // @@protoc_insertion_point(class_scope:Protocol.S_EnterGame)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    uint64_t accountid_;
    bool success_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Protocol_2eproto;
};
// -------------------------------------------------------------------

class S_MyPlayer final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.S_MyPlayer) */ {
 public:
  inline S_MyPlayer() : S_MyPlayer(nullptr) {}
  ~S_MyPlayer() override;
  explicit PROTOBUF_CONSTEXPR S_MyPlayer(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  S_MyPlayer(const S_MyPlayer& from);
  S_MyPlayer(S_MyPlayer&& from) noexcept
    : S_MyPlayer() {
    *this = ::std::move(from);
  }

  inline S_MyPlayer& operator=(const S_MyPlayer& from) {
    CopyFrom(from);
    return *this;
  }
  inline S_MyPlayer& operator=(S_MyPlayer&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const S_MyPlayer& default_instance() {
    return *internal_default_instance();
  }
  static inline const S_MyPlayer* internal_default_instance() {
    return reinterpret_cast<const S_MyPlayer*>(
               &_S_MyPlayer_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(S_MyPlayer& a, S_MyPlayer& b) {
    a.Swap(&b);
  }
  inline void Swap(S_MyPlayer* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(S_MyPlayer* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  S_MyPlayer* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<S_MyPlayer>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const S_MyPlayer& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const S_MyPlayer& from) {
    S_MyPlayer::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(S_MyPlayer* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.S_MyPlayer";
  }
  protected:
  explicit S_MyPlayer(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kObjectidFieldNumber = 1,
    kPosxFieldNumber = 2,
    kPosyFieldNumber = 3,
    kDirFieldNumber = 4,
    kStateFieldNumber = 5,
    kMovespeedFieldNumber = 6,
  };
  // uint64 objectid = 1;
  void clear_objectid();
  uint64_t objectid() const;
  void set_objectid(uint64_t value);
  private:
  uint64_t _internal_objectid() const;
  void _internal_set_objectid(uint64_t value);
  public:

  // float posx = 2;
  void clear_posx();
  float posx() const;
  void set_posx(float value);
  private:
  float _internal_posx() const;
  void _internal_set_posx(float value);
  public:

  // float posy = 3;
  void clear_posy();
  float posy() const;
  void set_posy(float value);
  private:
  float _internal_posy() const;
  void _internal_set_posy(float value);
  public:

  // int32 dir = 4;
  void clear_dir();
  int32_t dir() const;
  void set_dir(int32_t value);
  private:
  int32_t _internal_dir() const;
  void _internal_set_dir(int32_t value);
  public:

  // int32 state = 5;
  void clear_state();
  int32_t state() const;
  void set_state(int32_t value);
  private:
  int32_t _internal_state() const;
  void _internal_set_state(int32_t value);
  public:

  // float movespeed = 6;
  void clear_movespeed();
  float movespeed() const;
  void set_movespeed(float value);
  private:
  float _internal_movespeed() const;
  void _internal_set_movespeed(float value);
  public:

  // @@protoc_insertion_point(class_scope:Protocol.S_MyPlayer)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    uint64_t objectid_;
    float posx_;
    float posy_;
    int32_t dir_;
    int32_t state_;
    float movespeed_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Protocol_2eproto;
};
// -------------------------------------------------------------------

class S_AddObject final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.S_AddObject) */ {
 public:
  inline S_AddObject() : S_AddObject(nullptr) {}
  ~S_AddObject() override;
  explicit PROTOBUF_CONSTEXPR S_AddObject(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  S_AddObject(const S_AddObject& from);
  S_AddObject(S_AddObject&& from) noexcept
    : S_AddObject() {
    *this = ::std::move(from);
  }

  inline S_AddObject& operator=(const S_AddObject& from) {
    CopyFrom(from);
    return *this;
  }
  inline S_AddObject& operator=(S_AddObject&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const S_AddObject& default_instance() {
    return *internal_default_instance();
  }
  static inline const S_AddObject* internal_default_instance() {
    return reinterpret_cast<const S_AddObject*>(
               &_S_AddObject_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(S_AddObject& a, S_AddObject& b) {
    a.Swap(&b);
  }
  inline void Swap(S_AddObject* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(S_AddObject* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  S_AddObject* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<S_AddObject>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const S_AddObject& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const S_AddObject& from) {
    S_AddObject::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(S_AddObject* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.S_AddObject";
  }
  protected:
  explicit S_AddObject(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kObjectidsFieldNumber = 1,
    kObjecttypesFieldNumber = 2,
    kPosxsFieldNumber = 3,
    kPosysFieldNumber = 4,
    kStatesFieldNumber = 5,
    kDirsFieldNumber = 6,
    kMovespeedsFieldNumber = 7,
  };
  // repeated uint64 objectids = 1;
  int objectids_size() const;
  private:
  int _internal_objectids_size() const;
  public:
  void clear_objectids();
  private:
  uint64_t _internal_objectids(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint64_t >&
      _internal_objectids() const;
  void _internal_add_objectids(uint64_t value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint64_t >*
      _internal_mutable_objectids();
  public:
  uint64_t objectids(int index) const;
  void set_objectids(int index, uint64_t value);
  void add_objectids(uint64_t value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint64_t >&
      objectids() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint64_t >*
      mutable_objectids();

  // repeated int32 objecttypes = 2;
  int objecttypes_size() const;
  private:
  int _internal_objecttypes_size() const;
  public:
  void clear_objecttypes();
  private:
  int32_t _internal_objecttypes(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >&
      _internal_objecttypes() const;
  void _internal_add_objecttypes(int32_t value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >*
      _internal_mutable_objecttypes();
  public:
  int32_t objecttypes(int index) const;
  void set_objecttypes(int index, int32_t value);
  void add_objecttypes(int32_t value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >&
      objecttypes() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >*
      mutable_objecttypes();

  // repeated float posxs = 3;
  int posxs_size() const;
  private:
  int _internal_posxs_size() const;
  public:
  void clear_posxs();
  private:
  float _internal_posxs(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
      _internal_posxs() const;
  void _internal_add_posxs(float value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
      _internal_mutable_posxs();
  public:
  float posxs(int index) const;
  void set_posxs(int index, float value);
  void add_posxs(float value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
      posxs() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
      mutable_posxs();

  // repeated float posys = 4;
  int posys_size() const;
  private:
  int _internal_posys_size() const;
  public:
  void clear_posys();
  private:
  float _internal_posys(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
      _internal_posys() const;
  void _internal_add_posys(float value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
      _internal_mutable_posys();
  public:
  float posys(int index) const;
  void set_posys(int index, float value);
  void add_posys(float value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
      posys() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
      mutable_posys();

  // repeated int32 states = 5;
  int states_size() const;
  private:
  int _internal_states_size() const;
  public:
  void clear_states();
  private:
  int32_t _internal_states(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >&
      _internal_states() const;
  void _internal_add_states(int32_t value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >*
      _internal_mutable_states();
  public:
  int32_t states(int index) const;
  void set_states(int index, int32_t value);
  void add_states(int32_t value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >&
      states() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >*
      mutable_states();

  // repeated int32 dirs = 6;
  int dirs_size() const;
  private:
  int _internal_dirs_size() const;
  public:
  void clear_dirs();
  private:
  int32_t _internal_dirs(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >&
      _internal_dirs() const;
  void _internal_add_dirs(int32_t value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >*
      _internal_mutable_dirs();
  public:
  int32_t dirs(int index) const;
  void set_dirs(int index, int32_t value);
  void add_dirs(int32_t value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >&
      dirs() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >*
      mutable_dirs();

  // repeated float movespeeds = 7;
  int movespeeds_size() const;
  private:
  int _internal_movespeeds_size() const;
  public:
  void clear_movespeeds();
  private:
  float _internal_movespeeds(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
      _internal_movespeeds() const;
  void _internal_add_movespeeds(float value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
      _internal_mutable_movespeeds();
  public:
  float movespeeds(int index) const;
  void set_movespeeds(int index, float value);
  void add_movespeeds(float value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
      movespeeds() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
      mutable_movespeeds();

  // @@protoc_insertion_point(class_scope:Protocol.S_AddObject)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint64_t > objectids_;
    mutable std::atomic<int> _objectids_cached_byte_size_;
    ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t > objecttypes_;
    mutable std::atomic<int> _objecttypes_cached_byte_size_;
    ::PROTOBUF_NAMESPACE_ID::RepeatedField< float > posxs_;
    ::PROTOBUF_NAMESPACE_ID::RepeatedField< float > posys_;
    ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t > states_;
    mutable std::atomic<int> _states_cached_byte_size_;
    ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t > dirs_;
    mutable std::atomic<int> _dirs_cached_byte_size_;
    ::PROTOBUF_NAMESPACE_ID::RepeatedField< float > movespeeds_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Protocol_2eproto;
};
// -------------------------------------------------------------------

class S_RemoveObject final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.S_RemoveObject) */ {
 public:
  inline S_RemoveObject() : S_RemoveObject(nullptr) {}
  ~S_RemoveObject() override;
  explicit PROTOBUF_CONSTEXPR S_RemoveObject(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  S_RemoveObject(const S_RemoveObject& from);
  S_RemoveObject(S_RemoveObject&& from) noexcept
    : S_RemoveObject() {
    *this = ::std::move(from);
  }

  inline S_RemoveObject& operator=(const S_RemoveObject& from) {
    CopyFrom(from);
    return *this;
  }
  inline S_RemoveObject& operator=(S_RemoveObject&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const S_RemoveObject& default_instance() {
    return *internal_default_instance();
  }
  static inline const S_RemoveObject* internal_default_instance() {
    return reinterpret_cast<const S_RemoveObject*>(
               &_S_RemoveObject_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(S_RemoveObject& a, S_RemoveObject& b) {
    a.Swap(&b);
  }
  inline void Swap(S_RemoveObject* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(S_RemoveObject* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  S_RemoveObject* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<S_RemoveObject>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const S_RemoveObject& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const S_RemoveObject& from) {
    S_RemoveObject::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(S_RemoveObject* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.S_RemoveObject";
  }
  protected:
  explicit S_RemoveObject(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kObjectidsFieldNumber = 1,
  };
  // repeated uint64 objectids = 1;
  int objectids_size() const;
  private:
  int _internal_objectids_size() const;
  public:
  void clear_objectids();
  private:
  uint64_t _internal_objectids(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint64_t >&
      _internal_objectids() const;
  void _internal_add_objectids(uint64_t value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint64_t >*
      _internal_mutable_objectids();
  public:
  uint64_t objectids(int index) const;
  void set_objectids(int index, uint64_t value);
  void add_objectids(uint64_t value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint64_t >&
      objectids() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint64_t >*
      mutable_objectids();

  // @@protoc_insertion_point(class_scope:Protocol.S_RemoveObject)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint64_t > objectids_;
    mutable std::atomic<int> _objectids_cached_byte_size_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Protocol_2eproto;
};
// -------------------------------------------------------------------

class C_Move final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.C_Move) */ {
 public:
  inline C_Move() : C_Move(nullptr) {}
  ~C_Move() override;
  explicit PROTOBUF_CONSTEXPR C_Move(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  C_Move(const C_Move& from);
  C_Move(C_Move&& from) noexcept
    : C_Move() {
    *this = ::std::move(from);
  }

  inline C_Move& operator=(const C_Move& from) {
    CopyFrom(from);
    return *this;
  }
  inline C_Move& operator=(C_Move&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const C_Move& default_instance() {
    return *internal_default_instance();
  }
  static inline const C_Move* internal_default_instance() {
    return reinterpret_cast<const C_Move*>(
               &_C_Move_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(C_Move& a, C_Move& b) {
    a.Swap(&b);
  }
  inline void Swap(C_Move* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(C_Move* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  C_Move* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<C_Move>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const C_Move& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const C_Move& from) {
    C_Move::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(C_Move* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.C_Move";
  }
  protected:
  explicit C_Move(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kObjectidFieldNumber = 1,
    kStateFieldNumber = 2,
    kDirFieldNumber = 3,
    kPosxFieldNumber = 4,
    kPosyFieldNumber = 5,
  };
  // uint64 objectid = 1;
  void clear_objectid();
  uint64_t objectid() const;
  void set_objectid(uint64_t value);
  private:
  uint64_t _internal_objectid() const;
  void _internal_set_objectid(uint64_t value);
  public:

  // uint32 state = 2;
  void clear_state();
  uint32_t state() const;
  void set_state(uint32_t value);
  private:
  uint32_t _internal_state() const;
  void _internal_set_state(uint32_t value);
  public:

  // int32 dir = 3;
  void clear_dir();
  int32_t dir() const;
  void set_dir(int32_t value);
  private:
  int32_t _internal_dir() const;
  void _internal_set_dir(int32_t value);
  public:

  // float posx = 4;
  void clear_posx();
  float posx() const;
  void set_posx(float value);
  private:
  float _internal_posx() const;
  void _internal_set_posx(float value);
  public:

  // float posy = 5;
  void clear_posy();
  float posy() const;
  void set_posy(float value);
  private:
  float _internal_posy() const;
  void _internal_set_posy(float value);
  public:

  // @@protoc_insertion_point(class_scope:Protocol.C_Move)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    uint64_t objectid_;
    uint32_t state_;
    int32_t dir_;
    float posx_;
    float posy_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Protocol_2eproto;
};
// -------------------------------------------------------------------

class S_Move final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.S_Move) */ {
 public:
  inline S_Move() : S_Move(nullptr) {}
  ~S_Move() override;
  explicit PROTOBUF_CONSTEXPR S_Move(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  S_Move(const S_Move& from);
  S_Move(S_Move&& from) noexcept
    : S_Move() {
    *this = ::std::move(from);
  }

  inline S_Move& operator=(const S_Move& from) {
    CopyFrom(from);
    return *this;
  }
  inline S_Move& operator=(S_Move&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const S_Move& default_instance() {
    return *internal_default_instance();
  }
  static inline const S_Move* internal_default_instance() {
    return reinterpret_cast<const S_Move*>(
               &_S_Move_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    5;

  friend void swap(S_Move& a, S_Move& b) {
    a.Swap(&b);
  }
  inline void Swap(S_Move* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(S_Move* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  S_Move* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<S_Move>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const S_Move& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const S_Move& from) {
    S_Move::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(S_Move* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.S_Move";
  }
  protected:
  explicit S_Move(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kObjectidFieldNumber = 1,
    kStateFieldNumber = 2,
    kDirFieldNumber = 3,
    kPosxFieldNumber = 4,
    kPosyFieldNumber = 5,
    kNeedsyncFieldNumber = 6,
  };
  // uint64 objectid = 1;
  void clear_objectid();
  uint64_t objectid() const;
  void set_objectid(uint64_t value);
  private:
  uint64_t _internal_objectid() const;
  void _internal_set_objectid(uint64_t value);
  public:

  // uint32 state = 2;
  void clear_state();
  uint32_t state() const;
  void set_state(uint32_t value);
  private:
  uint32_t _internal_state() const;
  void _internal_set_state(uint32_t value);
  public:

  // int32 dir = 3;
  void clear_dir();
  int32_t dir() const;
  void set_dir(int32_t value);
  private:
  int32_t _internal_dir() const;
  void _internal_set_dir(int32_t value);
  public:

  // float posx = 4;
  void clear_posx();
  float posx() const;
  void set_posx(float value);
  private:
  float _internal_posx() const;
  void _internal_set_posx(float value);
  public:

  // float posy = 5;
  void clear_posy();
  float posy() const;
  void set_posy(float value);
  private:
  float _internal_posy() const;
  void _internal_set_posy(float value);
  public:

  // bool needsync = 6;
  void clear_needsync();
  bool needsync() const;
  void set_needsync(bool value);
  private:
  bool _internal_needsync() const;
  void _internal_set_needsync(bool value);
  public:

  // @@protoc_insertion_point(class_scope:Protocol.S_Move)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    uint64_t objectid_;
    uint32_t state_;
    int32_t dir_;
    float posx_;
    float posy_;
    bool needsync_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Protocol_2eproto;
};
// -------------------------------------------------------------------

class S_Tilemap final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.S_Tilemap) */ {
 public:
  inline S_Tilemap() : S_Tilemap(nullptr) {}
  ~S_Tilemap() override;
  explicit PROTOBUF_CONSTEXPR S_Tilemap(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  S_Tilemap(const S_Tilemap& from);
  S_Tilemap(S_Tilemap&& from) noexcept
    : S_Tilemap() {
    *this = ::std::move(from);
  }

  inline S_Tilemap& operator=(const S_Tilemap& from) {
    CopyFrom(from);
    return *this;
  }
  inline S_Tilemap& operator=(S_Tilemap&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const S_Tilemap& default_instance() {
    return *internal_default_instance();
  }
  static inline const S_Tilemap* internal_default_instance() {
    return reinterpret_cast<const S_Tilemap*>(
               &_S_Tilemap_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    6;

  friend void swap(S_Tilemap& a, S_Tilemap& b) {
    a.Swap(&b);
  }
  inline void Swap(S_Tilemap* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(S_Tilemap* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  S_Tilemap* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<S_Tilemap>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const S_Tilemap& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const S_Tilemap& from) {
    S_Tilemap::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(S_Tilemap* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.S_Tilemap";
  }
  protected:
  explicit S_Tilemap(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kValuesFieldNumber = 3,
    kMapsizexFieldNumber = 1,
    kMapsizeyFieldNumber = 2,
  };
  // repeated int32 values = 3;
  int values_size() const;
  private:
  int _internal_values_size() const;
  public:
  void clear_values();
  private:
  int32_t _internal_values(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >&
      _internal_values() const;
  void _internal_add_values(int32_t value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >*
      _internal_mutable_values();
  public:
  int32_t values(int index) const;
  void set_values(int index, int32_t value);
  void add_values(int32_t value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >&
      values() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >*
      mutable_values();

  // int32 mapsizex = 1;
  void clear_mapsizex();
  int32_t mapsizex() const;
  void set_mapsizex(int32_t value);
  private:
  int32_t _internal_mapsizex() const;
  void _internal_set_mapsizex(int32_t value);
  public:

  // int32 mapsizey = 2;
  void clear_mapsizey();
  int32_t mapsizey() const;
  void set_mapsizey(int32_t value);
  private:
  int32_t _internal_mapsizey() const;
  void _internal_set_mapsizey(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:Protocol.S_Tilemap)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t > values_;
    mutable std::atomic<int> _values_cached_byte_size_;
    int32_t mapsizex_;
    int32_t mapsizey_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Protocol_2eproto;
};
// -------------------------------------------------------------------

class C_WaterBomb final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.C_WaterBomb) */ {
 public:
  inline C_WaterBomb() : C_WaterBomb(nullptr) {}
  ~C_WaterBomb() override;
  explicit PROTOBUF_CONSTEXPR C_WaterBomb(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  C_WaterBomb(const C_WaterBomb& from);
  C_WaterBomb(C_WaterBomb&& from) noexcept
    : C_WaterBomb() {
    *this = ::std::move(from);
  }

  inline C_WaterBomb& operator=(const C_WaterBomb& from) {
    CopyFrom(from);
    return *this;
  }
  inline C_WaterBomb& operator=(C_WaterBomb&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const C_WaterBomb& default_instance() {
    return *internal_default_instance();
  }
  static inline const C_WaterBomb* internal_default_instance() {
    return reinterpret_cast<const C_WaterBomb*>(
               &_C_WaterBomb_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    7;

  friend void swap(C_WaterBomb& a, C_WaterBomb& b) {
    a.Swap(&b);
  }
  inline void Swap(C_WaterBomb* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(C_WaterBomb* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  C_WaterBomb* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<C_WaterBomb>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const C_WaterBomb& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const C_WaterBomb& from) {
    C_WaterBomb::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(C_WaterBomb* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.C_WaterBomb";
  }
  protected:
  explicit C_WaterBomb(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTileposxFieldNumber = 1,
    kTileposyFieldNumber = 2,
  };
  // int32 tileposx = 1;
  void clear_tileposx();
  int32_t tileposx() const;
  void set_tileposx(int32_t value);
  private:
  int32_t _internal_tileposx() const;
  void _internal_set_tileposx(int32_t value);
  public:

  // int32 tileposy = 2;
  void clear_tileposy();
  int32_t tileposy() const;
  void set_tileposy(int32_t value);
  private:
  int32_t _internal_tileposy() const;
  void _internal_set_tileposy(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:Protocol.C_WaterBomb)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    int32_t tileposx_;
    int32_t tileposy_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Protocol_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// S_EnterGame

// bool success = 1;
inline void S_EnterGame::clear_success() {
  _impl_.success_ = false;
}
inline bool S_EnterGame::_internal_success() const {
  return _impl_.success_;
}
inline bool S_EnterGame::success() const {
  // @@protoc_insertion_point(field_get:Protocol.S_EnterGame.success)
  return _internal_success();
}
inline void S_EnterGame::_internal_set_success(bool value) {
  
  _impl_.success_ = value;
}
inline void S_EnterGame::set_success(bool value) {
  _internal_set_success(value);
  // @@protoc_insertion_point(field_set:Protocol.S_EnterGame.success)
}

// uint64 accountId = 2;
inline void S_EnterGame::clear_accountid() {
  _impl_.accountid_ = uint64_t{0u};
}
inline uint64_t S_EnterGame::_internal_accountid() const {
  return _impl_.accountid_;
}
inline uint64_t S_EnterGame::accountid() const {
  // @@protoc_insertion_point(field_get:Protocol.S_EnterGame.accountId)
  return _internal_accountid();
}
inline void S_EnterGame::_internal_set_accountid(uint64_t value) {
  
  _impl_.accountid_ = value;
}
inline void S_EnterGame::set_accountid(uint64_t value) {
  _internal_set_accountid(value);
  // @@protoc_insertion_point(field_set:Protocol.S_EnterGame.accountId)
}

// -------------------------------------------------------------------

// S_MyPlayer

// uint64 objectid = 1;
inline void S_MyPlayer::clear_objectid() {
  _impl_.objectid_ = uint64_t{0u};
}
inline uint64_t S_MyPlayer::_internal_objectid() const {
  return _impl_.objectid_;
}
inline uint64_t S_MyPlayer::objectid() const {
  // @@protoc_insertion_point(field_get:Protocol.S_MyPlayer.objectid)
  return _internal_objectid();
}
inline void S_MyPlayer::_internal_set_objectid(uint64_t value) {
  
  _impl_.objectid_ = value;
}
inline void S_MyPlayer::set_objectid(uint64_t value) {
  _internal_set_objectid(value);
  // @@protoc_insertion_point(field_set:Protocol.S_MyPlayer.objectid)
}

// float posx = 2;
inline void S_MyPlayer::clear_posx() {
  _impl_.posx_ = 0;
}
inline float S_MyPlayer::_internal_posx() const {
  return _impl_.posx_;
}
inline float S_MyPlayer::posx() const {
  // @@protoc_insertion_point(field_get:Protocol.S_MyPlayer.posx)
  return _internal_posx();
}
inline void S_MyPlayer::_internal_set_posx(float value) {
  
  _impl_.posx_ = value;
}
inline void S_MyPlayer::set_posx(float value) {
  _internal_set_posx(value);
  // @@protoc_insertion_point(field_set:Protocol.S_MyPlayer.posx)
}

// float posy = 3;
inline void S_MyPlayer::clear_posy() {
  _impl_.posy_ = 0;
}
inline float S_MyPlayer::_internal_posy() const {
  return _impl_.posy_;
}
inline float S_MyPlayer::posy() const {
  // @@protoc_insertion_point(field_get:Protocol.S_MyPlayer.posy)
  return _internal_posy();
}
inline void S_MyPlayer::_internal_set_posy(float value) {
  
  _impl_.posy_ = value;
}
inline void S_MyPlayer::set_posy(float value) {
  _internal_set_posy(value);
  // @@protoc_insertion_point(field_set:Protocol.S_MyPlayer.posy)
}

// int32 dir = 4;
inline void S_MyPlayer::clear_dir() {
  _impl_.dir_ = 0;
}
inline int32_t S_MyPlayer::_internal_dir() const {
  return _impl_.dir_;
}
inline int32_t S_MyPlayer::dir() const {
  // @@protoc_insertion_point(field_get:Protocol.S_MyPlayer.dir)
  return _internal_dir();
}
inline void S_MyPlayer::_internal_set_dir(int32_t value) {
  
  _impl_.dir_ = value;
}
inline void S_MyPlayer::set_dir(int32_t value) {
  _internal_set_dir(value);
  // @@protoc_insertion_point(field_set:Protocol.S_MyPlayer.dir)
}

// int32 state = 5;
inline void S_MyPlayer::clear_state() {
  _impl_.state_ = 0;
}
inline int32_t S_MyPlayer::_internal_state() const {
  return _impl_.state_;
}
inline int32_t S_MyPlayer::state() const {
  // @@protoc_insertion_point(field_get:Protocol.S_MyPlayer.state)
  return _internal_state();
}
inline void S_MyPlayer::_internal_set_state(int32_t value) {
  
  _impl_.state_ = value;
}
inline void S_MyPlayer::set_state(int32_t value) {
  _internal_set_state(value);
  // @@protoc_insertion_point(field_set:Protocol.S_MyPlayer.state)
}

// float movespeed = 6;
inline void S_MyPlayer::clear_movespeed() {
  _impl_.movespeed_ = 0;
}
inline float S_MyPlayer::_internal_movespeed() const {
  return _impl_.movespeed_;
}
inline float S_MyPlayer::movespeed() const {
  // @@protoc_insertion_point(field_get:Protocol.S_MyPlayer.movespeed)
  return _internal_movespeed();
}
inline void S_MyPlayer::_internal_set_movespeed(float value) {
  
  _impl_.movespeed_ = value;
}
inline void S_MyPlayer::set_movespeed(float value) {
  _internal_set_movespeed(value);
  // @@protoc_insertion_point(field_set:Protocol.S_MyPlayer.movespeed)
}

// -------------------------------------------------------------------

// S_AddObject

// repeated uint64 objectids = 1;
inline int S_AddObject::_internal_objectids_size() const {
  return _impl_.objectids_.size();
}
inline int S_AddObject::objectids_size() const {
  return _internal_objectids_size();
}
inline void S_AddObject::clear_objectids() {
  _impl_.objectids_.Clear();
}
inline uint64_t S_AddObject::_internal_objectids(int index) const {
  return _impl_.objectids_.Get(index);
}
inline uint64_t S_AddObject::objectids(int index) const {
  // @@protoc_insertion_point(field_get:Protocol.S_AddObject.objectids)
  return _internal_objectids(index);
}
inline void S_AddObject::set_objectids(int index, uint64_t value) {
  _impl_.objectids_.Set(index, value);
  // @@protoc_insertion_point(field_set:Protocol.S_AddObject.objectids)
}
inline void S_AddObject::_internal_add_objectids(uint64_t value) {
  _impl_.objectids_.Add(value);
}
inline void S_AddObject::add_objectids(uint64_t value) {
  _internal_add_objectids(value);
  // @@protoc_insertion_point(field_add:Protocol.S_AddObject.objectids)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint64_t >&
S_AddObject::_internal_objectids() const {
  return _impl_.objectids_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint64_t >&
S_AddObject::objectids() const {
  // @@protoc_insertion_point(field_list:Protocol.S_AddObject.objectids)
  return _internal_objectids();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint64_t >*
S_AddObject::_internal_mutable_objectids() {
  return &_impl_.objectids_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint64_t >*
S_AddObject::mutable_objectids() {
  // @@protoc_insertion_point(field_mutable_list:Protocol.S_AddObject.objectids)
  return _internal_mutable_objectids();
}

// repeated int32 objecttypes = 2;
inline int S_AddObject::_internal_objecttypes_size() const {
  return _impl_.objecttypes_.size();
}
inline int S_AddObject::objecttypes_size() const {
  return _internal_objecttypes_size();
}
inline void S_AddObject::clear_objecttypes() {
  _impl_.objecttypes_.Clear();
}
inline int32_t S_AddObject::_internal_objecttypes(int index) const {
  return _impl_.objecttypes_.Get(index);
}
inline int32_t S_AddObject::objecttypes(int index) const {
  // @@protoc_insertion_point(field_get:Protocol.S_AddObject.objecttypes)
  return _internal_objecttypes(index);
}
inline void S_AddObject::set_objecttypes(int index, int32_t value) {
  _impl_.objecttypes_.Set(index, value);
  // @@protoc_insertion_point(field_set:Protocol.S_AddObject.objecttypes)
}
inline void S_AddObject::_internal_add_objecttypes(int32_t value) {
  _impl_.objecttypes_.Add(value);
}
inline void S_AddObject::add_objecttypes(int32_t value) {
  _internal_add_objecttypes(value);
  // @@protoc_insertion_point(field_add:Protocol.S_AddObject.objecttypes)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >&
S_AddObject::_internal_objecttypes() const {
  return _impl_.objecttypes_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >&
S_AddObject::objecttypes() const {
  // @@protoc_insertion_point(field_list:Protocol.S_AddObject.objecttypes)
  return _internal_objecttypes();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >*
S_AddObject::_internal_mutable_objecttypes() {
  return &_impl_.objecttypes_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >*
S_AddObject::mutable_objecttypes() {
  // @@protoc_insertion_point(field_mutable_list:Protocol.S_AddObject.objecttypes)
  return _internal_mutable_objecttypes();
}

// repeated float posxs = 3;
inline int S_AddObject::_internal_posxs_size() const {
  return _impl_.posxs_.size();
}
inline int S_AddObject::posxs_size() const {
  return _internal_posxs_size();
}
inline void S_AddObject::clear_posxs() {
  _impl_.posxs_.Clear();
}
inline float S_AddObject::_internal_posxs(int index) const {
  return _impl_.posxs_.Get(index);
}
inline float S_AddObject::posxs(int index) const {
  // @@protoc_insertion_point(field_get:Protocol.S_AddObject.posxs)
  return _internal_posxs(index);
}
inline void S_AddObject::set_posxs(int index, float value) {
  _impl_.posxs_.Set(index, value);
  // @@protoc_insertion_point(field_set:Protocol.S_AddObject.posxs)
}
inline void S_AddObject::_internal_add_posxs(float value) {
  _impl_.posxs_.Add(value);
}
inline void S_AddObject::add_posxs(float value) {
  _internal_add_posxs(value);
  // @@protoc_insertion_point(field_add:Protocol.S_AddObject.posxs)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
S_AddObject::_internal_posxs() const {
  return _impl_.posxs_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
S_AddObject::posxs() const {
  // @@protoc_insertion_point(field_list:Protocol.S_AddObject.posxs)
  return _internal_posxs();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
S_AddObject::_internal_mutable_posxs() {
  return &_impl_.posxs_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
S_AddObject::mutable_posxs() {
  // @@protoc_insertion_point(field_mutable_list:Protocol.S_AddObject.posxs)
  return _internal_mutable_posxs();
}

// repeated float posys = 4;
inline int S_AddObject::_internal_posys_size() const {
  return _impl_.posys_.size();
}
inline int S_AddObject::posys_size() const {
  return _internal_posys_size();
}
inline void S_AddObject::clear_posys() {
  _impl_.posys_.Clear();
}
inline float S_AddObject::_internal_posys(int index) const {
  return _impl_.posys_.Get(index);
}
inline float S_AddObject::posys(int index) const {
  // @@protoc_insertion_point(field_get:Protocol.S_AddObject.posys)
  return _internal_posys(index);
}
inline void S_AddObject::set_posys(int index, float value) {
  _impl_.posys_.Set(index, value);
  // @@protoc_insertion_point(field_set:Protocol.S_AddObject.posys)
}
inline void S_AddObject::_internal_add_posys(float value) {
  _impl_.posys_.Add(value);
}
inline void S_AddObject::add_posys(float value) {
  _internal_add_posys(value);
  // @@protoc_insertion_point(field_add:Protocol.S_AddObject.posys)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
S_AddObject::_internal_posys() const {
  return _impl_.posys_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
S_AddObject::posys() const {
  // @@protoc_insertion_point(field_list:Protocol.S_AddObject.posys)
  return _internal_posys();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
S_AddObject::_internal_mutable_posys() {
  return &_impl_.posys_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
S_AddObject::mutable_posys() {
  // @@protoc_insertion_point(field_mutable_list:Protocol.S_AddObject.posys)
  return _internal_mutable_posys();
}

// repeated int32 states = 5;
inline int S_AddObject::_internal_states_size() const {
  return _impl_.states_.size();
}
inline int S_AddObject::states_size() const {
  return _internal_states_size();
}
inline void S_AddObject::clear_states() {
  _impl_.states_.Clear();
}
inline int32_t S_AddObject::_internal_states(int index) const {
  return _impl_.states_.Get(index);
}
inline int32_t S_AddObject::states(int index) const {
  // @@protoc_insertion_point(field_get:Protocol.S_AddObject.states)
  return _internal_states(index);
}
inline void S_AddObject::set_states(int index, int32_t value) {
  _impl_.states_.Set(index, value);
  // @@protoc_insertion_point(field_set:Protocol.S_AddObject.states)
}
inline void S_AddObject::_internal_add_states(int32_t value) {
  _impl_.states_.Add(value);
}
inline void S_AddObject::add_states(int32_t value) {
  _internal_add_states(value);
  // @@protoc_insertion_point(field_add:Protocol.S_AddObject.states)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >&
S_AddObject::_internal_states() const {
  return _impl_.states_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >&
S_AddObject::states() const {
  // @@protoc_insertion_point(field_list:Protocol.S_AddObject.states)
  return _internal_states();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >*
S_AddObject::_internal_mutable_states() {
  return &_impl_.states_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >*
S_AddObject::mutable_states() {
  // @@protoc_insertion_point(field_mutable_list:Protocol.S_AddObject.states)
  return _internal_mutable_states();
}

// repeated int32 dirs = 6;
inline int S_AddObject::_internal_dirs_size() const {
  return _impl_.dirs_.size();
}
inline int S_AddObject::dirs_size() const {
  return _internal_dirs_size();
}
inline void S_AddObject::clear_dirs() {
  _impl_.dirs_.Clear();
}
inline int32_t S_AddObject::_internal_dirs(int index) const {
  return _impl_.dirs_.Get(index);
}
inline int32_t S_AddObject::dirs(int index) const {
  // @@protoc_insertion_point(field_get:Protocol.S_AddObject.dirs)
  return _internal_dirs(index);
}
inline void S_AddObject::set_dirs(int index, int32_t value) {
  _impl_.dirs_.Set(index, value);
  // @@protoc_insertion_point(field_set:Protocol.S_AddObject.dirs)
}
inline void S_AddObject::_internal_add_dirs(int32_t value) {
  _impl_.dirs_.Add(value);
}
inline void S_AddObject::add_dirs(int32_t value) {
  _internal_add_dirs(value);
  // @@protoc_insertion_point(field_add:Protocol.S_AddObject.dirs)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >&
S_AddObject::_internal_dirs() const {
  return _impl_.dirs_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >&
S_AddObject::dirs() const {
  // @@protoc_insertion_point(field_list:Protocol.S_AddObject.dirs)
  return _internal_dirs();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >*
S_AddObject::_internal_mutable_dirs() {
  return &_impl_.dirs_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >*
S_AddObject::mutable_dirs() {
  // @@protoc_insertion_point(field_mutable_list:Protocol.S_AddObject.dirs)
  return _internal_mutable_dirs();
}

// repeated float movespeeds = 7;
inline int S_AddObject::_internal_movespeeds_size() const {
  return _impl_.movespeeds_.size();
}
inline int S_AddObject::movespeeds_size() const {
  return _internal_movespeeds_size();
}
inline void S_AddObject::clear_movespeeds() {
  _impl_.movespeeds_.Clear();
}
inline float S_AddObject::_internal_movespeeds(int index) const {
  return _impl_.movespeeds_.Get(index);
}
inline float S_AddObject::movespeeds(int index) const {
  // @@protoc_insertion_point(field_get:Protocol.S_AddObject.movespeeds)
  return _internal_movespeeds(index);
}
inline void S_AddObject::set_movespeeds(int index, float value) {
  _impl_.movespeeds_.Set(index, value);
  // @@protoc_insertion_point(field_set:Protocol.S_AddObject.movespeeds)
}
inline void S_AddObject::_internal_add_movespeeds(float value) {
  _impl_.movespeeds_.Add(value);
}
inline void S_AddObject::add_movespeeds(float value) {
  _internal_add_movespeeds(value);
  // @@protoc_insertion_point(field_add:Protocol.S_AddObject.movespeeds)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
S_AddObject::_internal_movespeeds() const {
  return _impl_.movespeeds_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
S_AddObject::movespeeds() const {
  // @@protoc_insertion_point(field_list:Protocol.S_AddObject.movespeeds)
  return _internal_movespeeds();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
S_AddObject::_internal_mutable_movespeeds() {
  return &_impl_.movespeeds_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
S_AddObject::mutable_movespeeds() {
  // @@protoc_insertion_point(field_mutable_list:Protocol.S_AddObject.movespeeds)
  return _internal_mutable_movespeeds();
}

// -------------------------------------------------------------------

// S_RemoveObject

// repeated uint64 objectids = 1;
inline int S_RemoveObject::_internal_objectids_size() const {
  return _impl_.objectids_.size();
}
inline int S_RemoveObject::objectids_size() const {
  return _internal_objectids_size();
}
inline void S_RemoveObject::clear_objectids() {
  _impl_.objectids_.Clear();
}
inline uint64_t S_RemoveObject::_internal_objectids(int index) const {
  return _impl_.objectids_.Get(index);
}
inline uint64_t S_RemoveObject::objectids(int index) const {
  // @@protoc_insertion_point(field_get:Protocol.S_RemoveObject.objectids)
  return _internal_objectids(index);
}
inline void S_RemoveObject::set_objectids(int index, uint64_t value) {
  _impl_.objectids_.Set(index, value);
  // @@protoc_insertion_point(field_set:Protocol.S_RemoveObject.objectids)
}
inline void S_RemoveObject::_internal_add_objectids(uint64_t value) {
  _impl_.objectids_.Add(value);
}
inline void S_RemoveObject::add_objectids(uint64_t value) {
  _internal_add_objectids(value);
  // @@protoc_insertion_point(field_add:Protocol.S_RemoveObject.objectids)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint64_t >&
S_RemoveObject::_internal_objectids() const {
  return _impl_.objectids_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint64_t >&
S_RemoveObject::objectids() const {
  // @@protoc_insertion_point(field_list:Protocol.S_RemoveObject.objectids)
  return _internal_objectids();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint64_t >*
S_RemoveObject::_internal_mutable_objectids() {
  return &_impl_.objectids_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint64_t >*
S_RemoveObject::mutable_objectids() {
  // @@protoc_insertion_point(field_mutable_list:Protocol.S_RemoveObject.objectids)
  return _internal_mutable_objectids();
}

// -------------------------------------------------------------------

// C_Move

// uint64 objectid = 1;
inline void C_Move::clear_objectid() {
  _impl_.objectid_ = uint64_t{0u};
}
inline uint64_t C_Move::_internal_objectid() const {
  return _impl_.objectid_;
}
inline uint64_t C_Move::objectid() const {
  // @@protoc_insertion_point(field_get:Protocol.C_Move.objectid)
  return _internal_objectid();
}
inline void C_Move::_internal_set_objectid(uint64_t value) {
  
  _impl_.objectid_ = value;
}
inline void C_Move::set_objectid(uint64_t value) {
  _internal_set_objectid(value);
  // @@protoc_insertion_point(field_set:Protocol.C_Move.objectid)
}

// uint32 state = 2;
inline void C_Move::clear_state() {
  _impl_.state_ = 0u;
}
inline uint32_t C_Move::_internal_state() const {
  return _impl_.state_;
}
inline uint32_t C_Move::state() const {
  // @@protoc_insertion_point(field_get:Protocol.C_Move.state)
  return _internal_state();
}
inline void C_Move::_internal_set_state(uint32_t value) {
  
  _impl_.state_ = value;
}
inline void C_Move::set_state(uint32_t value) {
  _internal_set_state(value);
  // @@protoc_insertion_point(field_set:Protocol.C_Move.state)
}

// int32 dir = 3;
inline void C_Move::clear_dir() {
  _impl_.dir_ = 0;
}
inline int32_t C_Move::_internal_dir() const {
  return _impl_.dir_;
}
inline int32_t C_Move::dir() const {
  // @@protoc_insertion_point(field_get:Protocol.C_Move.dir)
  return _internal_dir();
}
inline void C_Move::_internal_set_dir(int32_t value) {
  
  _impl_.dir_ = value;
}
inline void C_Move::set_dir(int32_t value) {
  _internal_set_dir(value);
  // @@protoc_insertion_point(field_set:Protocol.C_Move.dir)
}

// float posx = 4;
inline void C_Move::clear_posx() {
  _impl_.posx_ = 0;
}
inline float C_Move::_internal_posx() const {
  return _impl_.posx_;
}
inline float C_Move::posx() const {
  // @@protoc_insertion_point(field_get:Protocol.C_Move.posx)
  return _internal_posx();
}
inline void C_Move::_internal_set_posx(float value) {
  
  _impl_.posx_ = value;
}
inline void C_Move::set_posx(float value) {
  _internal_set_posx(value);
  // @@protoc_insertion_point(field_set:Protocol.C_Move.posx)
}

// float posy = 5;
inline void C_Move::clear_posy() {
  _impl_.posy_ = 0;
}
inline float C_Move::_internal_posy() const {
  return _impl_.posy_;
}
inline float C_Move::posy() const {
  // @@protoc_insertion_point(field_get:Protocol.C_Move.posy)
  return _internal_posy();
}
inline void C_Move::_internal_set_posy(float value) {
  
  _impl_.posy_ = value;
}
inline void C_Move::set_posy(float value) {
  _internal_set_posy(value);
  // @@protoc_insertion_point(field_set:Protocol.C_Move.posy)
}

// -------------------------------------------------------------------

// S_Move

// uint64 objectid = 1;
inline void S_Move::clear_objectid() {
  _impl_.objectid_ = uint64_t{0u};
}
inline uint64_t S_Move::_internal_objectid() const {
  return _impl_.objectid_;
}
inline uint64_t S_Move::objectid() const {
  // @@protoc_insertion_point(field_get:Protocol.S_Move.objectid)
  return _internal_objectid();
}
inline void S_Move::_internal_set_objectid(uint64_t value) {
  
  _impl_.objectid_ = value;
}
inline void S_Move::set_objectid(uint64_t value) {
  _internal_set_objectid(value);
  // @@protoc_insertion_point(field_set:Protocol.S_Move.objectid)
}

// uint32 state = 2;
inline void S_Move::clear_state() {
  _impl_.state_ = 0u;
}
inline uint32_t S_Move::_internal_state() const {
  return _impl_.state_;
}
inline uint32_t S_Move::state() const {
  // @@protoc_insertion_point(field_get:Protocol.S_Move.state)
  return _internal_state();
}
inline void S_Move::_internal_set_state(uint32_t value) {
  
  _impl_.state_ = value;
}
inline void S_Move::set_state(uint32_t value) {
  _internal_set_state(value);
  // @@protoc_insertion_point(field_set:Protocol.S_Move.state)
}

// int32 dir = 3;
inline void S_Move::clear_dir() {
  _impl_.dir_ = 0;
}
inline int32_t S_Move::_internal_dir() const {
  return _impl_.dir_;
}
inline int32_t S_Move::dir() const {
  // @@protoc_insertion_point(field_get:Protocol.S_Move.dir)
  return _internal_dir();
}
inline void S_Move::_internal_set_dir(int32_t value) {
  
  _impl_.dir_ = value;
}
inline void S_Move::set_dir(int32_t value) {
  _internal_set_dir(value);
  // @@protoc_insertion_point(field_set:Protocol.S_Move.dir)
}

// float posx = 4;
inline void S_Move::clear_posx() {
  _impl_.posx_ = 0;
}
inline float S_Move::_internal_posx() const {
  return _impl_.posx_;
}
inline float S_Move::posx() const {
  // @@protoc_insertion_point(field_get:Protocol.S_Move.posx)
  return _internal_posx();
}
inline void S_Move::_internal_set_posx(float value) {
  
  _impl_.posx_ = value;
}
inline void S_Move::set_posx(float value) {
  _internal_set_posx(value);
  // @@protoc_insertion_point(field_set:Protocol.S_Move.posx)
}

// float posy = 5;
inline void S_Move::clear_posy() {
  _impl_.posy_ = 0;
}
inline float S_Move::_internal_posy() const {
  return _impl_.posy_;
}
inline float S_Move::posy() const {
  // @@protoc_insertion_point(field_get:Protocol.S_Move.posy)
  return _internal_posy();
}
inline void S_Move::_internal_set_posy(float value) {
  
  _impl_.posy_ = value;
}
inline void S_Move::set_posy(float value) {
  _internal_set_posy(value);
  // @@protoc_insertion_point(field_set:Protocol.S_Move.posy)
}

// bool needsync = 6;
inline void S_Move::clear_needsync() {
  _impl_.needsync_ = false;
}
inline bool S_Move::_internal_needsync() const {
  return _impl_.needsync_;
}
inline bool S_Move::needsync() const {
  // @@protoc_insertion_point(field_get:Protocol.S_Move.needsync)
  return _internal_needsync();
}
inline void S_Move::_internal_set_needsync(bool value) {
  
  _impl_.needsync_ = value;
}
inline void S_Move::set_needsync(bool value) {
  _internal_set_needsync(value);
  // @@protoc_insertion_point(field_set:Protocol.S_Move.needsync)
}

// -------------------------------------------------------------------

// S_Tilemap

// int32 mapsizex = 1;
inline void S_Tilemap::clear_mapsizex() {
  _impl_.mapsizex_ = 0;
}
inline int32_t S_Tilemap::_internal_mapsizex() const {
  return _impl_.mapsizex_;
}
inline int32_t S_Tilemap::mapsizex() const {
  // @@protoc_insertion_point(field_get:Protocol.S_Tilemap.mapsizex)
  return _internal_mapsizex();
}
inline void S_Tilemap::_internal_set_mapsizex(int32_t value) {
  
  _impl_.mapsizex_ = value;
}
inline void S_Tilemap::set_mapsizex(int32_t value) {
  _internal_set_mapsizex(value);
  // @@protoc_insertion_point(field_set:Protocol.S_Tilemap.mapsizex)
}

// int32 mapsizey = 2;
inline void S_Tilemap::clear_mapsizey() {
  _impl_.mapsizey_ = 0;
}
inline int32_t S_Tilemap::_internal_mapsizey() const {
  return _impl_.mapsizey_;
}
inline int32_t S_Tilemap::mapsizey() const {
  // @@protoc_insertion_point(field_get:Protocol.S_Tilemap.mapsizey)
  return _internal_mapsizey();
}
inline void S_Tilemap::_internal_set_mapsizey(int32_t value) {
  
  _impl_.mapsizey_ = value;
}
inline void S_Tilemap::set_mapsizey(int32_t value) {
  _internal_set_mapsizey(value);
  // @@protoc_insertion_point(field_set:Protocol.S_Tilemap.mapsizey)
}

// repeated int32 values = 3;
inline int S_Tilemap::_internal_values_size() const {
  return _impl_.values_.size();
}
inline int S_Tilemap::values_size() const {
  return _internal_values_size();
}
inline void S_Tilemap::clear_values() {
  _impl_.values_.Clear();
}
inline int32_t S_Tilemap::_internal_values(int index) const {
  return _impl_.values_.Get(index);
}
inline int32_t S_Tilemap::values(int index) const {
  // @@protoc_insertion_point(field_get:Protocol.S_Tilemap.values)
  return _internal_values(index);
}
inline void S_Tilemap::set_values(int index, int32_t value) {
  _impl_.values_.Set(index, value);
  // @@protoc_insertion_point(field_set:Protocol.S_Tilemap.values)
}
inline void S_Tilemap::_internal_add_values(int32_t value) {
  _impl_.values_.Add(value);
}
inline void S_Tilemap::add_values(int32_t value) {
  _internal_add_values(value);
  // @@protoc_insertion_point(field_add:Protocol.S_Tilemap.values)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >&
S_Tilemap::_internal_values() const {
  return _impl_.values_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >&
S_Tilemap::values() const {
  // @@protoc_insertion_point(field_list:Protocol.S_Tilemap.values)
  return _internal_values();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >*
S_Tilemap::_internal_mutable_values() {
  return &_impl_.values_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >*
S_Tilemap::mutable_values() {
  // @@protoc_insertion_point(field_mutable_list:Protocol.S_Tilemap.values)
  return _internal_mutable_values();
}

// -------------------------------------------------------------------

// C_WaterBomb

// int32 tileposx = 1;
inline void C_WaterBomb::clear_tileposx() {
  _impl_.tileposx_ = 0;
}
inline int32_t C_WaterBomb::_internal_tileposx() const {
  return _impl_.tileposx_;
}
inline int32_t C_WaterBomb::tileposx() const {
  // @@protoc_insertion_point(field_get:Protocol.C_WaterBomb.tileposx)
  return _internal_tileposx();
}
inline void C_WaterBomb::_internal_set_tileposx(int32_t value) {
  
  _impl_.tileposx_ = value;
}
inline void C_WaterBomb::set_tileposx(int32_t value) {
  _internal_set_tileposx(value);
  // @@protoc_insertion_point(field_set:Protocol.C_WaterBomb.tileposx)
}

// int32 tileposy = 2;
inline void C_WaterBomb::clear_tileposy() {
  _impl_.tileposy_ = 0;
}
inline int32_t C_WaterBomb::_internal_tileposy() const {
  return _impl_.tileposy_;
}
inline int32_t C_WaterBomb::tileposy() const {
  // @@protoc_insertion_point(field_get:Protocol.C_WaterBomb.tileposy)
  return _internal_tileposy();
}
inline void C_WaterBomb::_internal_set_tileposy(int32_t value) {
  
  _impl_.tileposy_ = value;
}
inline void C_WaterBomb::set_tileposy(int32_t value) {
  _internal_set_tileposy(value);
  // @@protoc_insertion_point(field_set:Protocol.C_WaterBomb.tileposy)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace Protocol

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_Protocol_2eproto
