// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Protocol.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_Protocol_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_Protocol_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "Struct.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_Protocol_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_Protocol_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_Protocol_2eproto;
namespace Protocol {
class C_Move;
struct C_MoveDefaultTypeInternal;
extern C_MoveDefaultTypeInternal _C_Move_default_instance_;
class C_WaterBomb;
struct C_WaterBombDefaultTypeInternal;
extern C_WaterBombDefaultTypeInternal _C_WaterBomb_default_instance_;
class S_EnterGame;
struct S_EnterGameDefaultTypeInternal;
extern S_EnterGameDefaultTypeInternal _S_EnterGame_default_instance_;
class S_Explode;
struct S_ExplodeDefaultTypeInternal;
extern S_ExplodeDefaultTypeInternal _S_Explode_default_instance_;
class S_Move;
struct S_MoveDefaultTypeInternal;
extern S_MoveDefaultTypeInternal _S_Move_default_instance_;
class S_MyPlayer;
struct S_MyPlayerDefaultTypeInternal;
extern S_MyPlayerDefaultTypeInternal _S_MyPlayer_default_instance_;
class S_OtherPlayers;
struct S_OtherPlayersDefaultTypeInternal;
extern S_OtherPlayersDefaultTypeInternal _S_OtherPlayers_default_instance_;
class S_PlayerLeave;
struct S_PlayerLeaveDefaultTypeInternal;
extern S_PlayerLeaveDefaultTypeInternal _S_PlayerLeave_default_instance_;
class S_Tilemap;
struct S_TilemapDefaultTypeInternal;
extern S_TilemapDefaultTypeInternal _S_Tilemap_default_instance_;
class S_WaterBomb;
struct S_WaterBombDefaultTypeInternal;
extern S_WaterBombDefaultTypeInternal _S_WaterBomb_default_instance_;
}  // namespace Protocol
PROTOBUF_NAMESPACE_OPEN
template<> ::Protocol::C_Move* Arena::CreateMaybeMessage<::Protocol::C_Move>(Arena*);
template<> ::Protocol::C_WaterBomb* Arena::CreateMaybeMessage<::Protocol::C_WaterBomb>(Arena*);
template<> ::Protocol::S_EnterGame* Arena::CreateMaybeMessage<::Protocol::S_EnterGame>(Arena*);
template<> ::Protocol::S_Explode* Arena::CreateMaybeMessage<::Protocol::S_Explode>(Arena*);
template<> ::Protocol::S_Move* Arena::CreateMaybeMessage<::Protocol::S_Move>(Arena*);
template<> ::Protocol::S_MyPlayer* Arena::CreateMaybeMessage<::Protocol::S_MyPlayer>(Arena*);
template<> ::Protocol::S_OtherPlayers* Arena::CreateMaybeMessage<::Protocol::S_OtherPlayers>(Arena*);
template<> ::Protocol::S_PlayerLeave* Arena::CreateMaybeMessage<::Protocol::S_PlayerLeave>(Arena*);
template<> ::Protocol::S_Tilemap* Arena::CreateMaybeMessage<::Protocol::S_Tilemap>(Arena*);
template<> ::Protocol::S_WaterBomb* Arena::CreateMaybeMessage<::Protocol::S_WaterBomb>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace Protocol {

// ===================================================================

class S_EnterGame final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.S_EnterGame) */ {
 public:
  inline S_EnterGame() : S_EnterGame(nullptr) {}
  ~S_EnterGame() override;
  explicit PROTOBUF_CONSTEXPR S_EnterGame(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  S_EnterGame(const S_EnterGame& from);
  S_EnterGame(S_EnterGame&& from) noexcept
    : S_EnterGame() {
    *this = ::std::move(from);
  }

  inline S_EnterGame& operator=(const S_EnterGame& from) {
    CopyFrom(from);
    return *this;
  }
  inline S_EnterGame& operator=(S_EnterGame&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const S_EnterGame& default_instance() {
    return *internal_default_instance();
  }
  static inline const S_EnterGame* internal_default_instance() {
    return reinterpret_cast<const S_EnterGame*>(
               &_S_EnterGame_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(S_EnterGame& a, S_EnterGame& b) {
    a.Swap(&b);
  }
  inline void Swap(S_EnterGame* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(S_EnterGame* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  S_EnterGame* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<S_EnterGame>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const S_EnterGame& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const S_EnterGame& from) {
    S_EnterGame::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(S_EnterGame* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.S_EnterGame";
  }
  protected:
  explicit S_EnterGame(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kAccountIdFieldNumber = 2,
    kSuccessFieldNumber = 1,
  };
  // uint64 accountId = 2;
  void clear_accountid();
  uint64_t accountid() const;
  void set_accountid(uint64_t value);
  private:
  uint64_t _internal_accountid() const;
  void _internal_set_accountid(uint64_t value);
  public:

  // bool success = 1;
  void clear_success();
  bool success() const;
  void set_success(bool value);
  private:
  bool _internal_success() const;
  void _internal_set_success(bool value);
  public:

  // @@protoc_insertion_point(class_scope:Protocol.S_EnterGame)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    uint64_t accountid_;
    bool success_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Protocol_2eproto;
};
// -------------------------------------------------------------------

class S_MyPlayer final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.S_MyPlayer) */ {
 public:
  inline S_MyPlayer() : S_MyPlayer(nullptr) {}
  ~S_MyPlayer() override;
  explicit PROTOBUF_CONSTEXPR S_MyPlayer(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  S_MyPlayer(const S_MyPlayer& from);
  S_MyPlayer(S_MyPlayer&& from) noexcept
    : S_MyPlayer() {
    *this = ::std::move(from);
  }

  inline S_MyPlayer& operator=(const S_MyPlayer& from) {
    CopyFrom(from);
    return *this;
  }
  inline S_MyPlayer& operator=(S_MyPlayer&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const S_MyPlayer& default_instance() {
    return *internal_default_instance();
  }
  static inline const S_MyPlayer* internal_default_instance() {
    return reinterpret_cast<const S_MyPlayer*>(
               &_S_MyPlayer_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(S_MyPlayer& a, S_MyPlayer& b) {
    a.Swap(&b);
  }
  inline void Swap(S_MyPlayer* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(S_MyPlayer* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  S_MyPlayer* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<S_MyPlayer>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const S_MyPlayer& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const S_MyPlayer& from) {
    S_MyPlayer::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(S_MyPlayer* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.S_MyPlayer";
  }
  protected:
  explicit S_MyPlayer(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kInfoFieldNumber = 1,
  };
  // .Protocol.PlayerInfo info = 1;
  bool has_info() const;
  private:
  bool _internal_has_info() const;
  public:
  void clear_info();
  const ::Protocol::PlayerInfo& info() const;
  PROTOBUF_NODISCARD ::Protocol::PlayerInfo* release_info();
  ::Protocol::PlayerInfo* mutable_info();
  void set_allocated_info(::Protocol::PlayerInfo* info);
  private:
  const ::Protocol::PlayerInfo& _internal_info() const;
  ::Protocol::PlayerInfo* _internal_mutable_info();
  public:
  void unsafe_arena_set_allocated_info(
      ::Protocol::PlayerInfo* info);
  ::Protocol::PlayerInfo* unsafe_arena_release_info();

  // @@protoc_insertion_point(class_scope:Protocol.S_MyPlayer)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::Protocol::PlayerInfo* info_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Protocol_2eproto;
};
// -------------------------------------------------------------------

class S_OtherPlayers final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.S_OtherPlayers) */ {
 public:
  inline S_OtherPlayers() : S_OtherPlayers(nullptr) {}
  ~S_OtherPlayers() override;
  explicit PROTOBUF_CONSTEXPR S_OtherPlayers(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  S_OtherPlayers(const S_OtherPlayers& from);
  S_OtherPlayers(S_OtherPlayers&& from) noexcept
    : S_OtherPlayers() {
    *this = ::std::move(from);
  }

  inline S_OtherPlayers& operator=(const S_OtherPlayers& from) {
    CopyFrom(from);
    return *this;
  }
  inline S_OtherPlayers& operator=(S_OtherPlayers&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const S_OtherPlayers& default_instance() {
    return *internal_default_instance();
  }
  static inline const S_OtherPlayers* internal_default_instance() {
    return reinterpret_cast<const S_OtherPlayers*>(
               &_S_OtherPlayers_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(S_OtherPlayers& a, S_OtherPlayers& b) {
    a.Swap(&b);
  }
  inline void Swap(S_OtherPlayers* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(S_OtherPlayers* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  S_OtherPlayers* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<S_OtherPlayers>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const S_OtherPlayers& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const S_OtherPlayers& from) {
    S_OtherPlayers::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(S_OtherPlayers* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.S_OtherPlayers";
  }
  protected:
  explicit S_OtherPlayers(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kInfosFieldNumber = 1,
  };
  // repeated .Protocol.PlayerInfo infos = 1;
  int infos_size() const;
  private:
  int _internal_infos_size() const;
  public:
  void clear_infos();
  ::Protocol::PlayerInfo* mutable_infos(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Protocol::PlayerInfo >*
      mutable_infos();
  private:
  const ::Protocol::PlayerInfo& _internal_infos(int index) const;
  ::Protocol::PlayerInfo* _internal_add_infos();
  public:
  const ::Protocol::PlayerInfo& infos(int index) const;
  ::Protocol::PlayerInfo* add_infos();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Protocol::PlayerInfo >&
      infos() const;

  // @@protoc_insertion_point(class_scope:Protocol.S_OtherPlayers)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Protocol::PlayerInfo > infos_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Protocol_2eproto;
};
// -------------------------------------------------------------------

class S_PlayerLeave final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.S_PlayerLeave) */ {
 public:
  inline S_PlayerLeave() : S_PlayerLeave(nullptr) {}
  ~S_PlayerLeave() override;
  explicit PROTOBUF_CONSTEXPR S_PlayerLeave(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  S_PlayerLeave(const S_PlayerLeave& from);
  S_PlayerLeave(S_PlayerLeave&& from) noexcept
    : S_PlayerLeave() {
    *this = ::std::move(from);
  }

  inline S_PlayerLeave& operator=(const S_PlayerLeave& from) {
    CopyFrom(from);
    return *this;
  }
  inline S_PlayerLeave& operator=(S_PlayerLeave&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const S_PlayerLeave& default_instance() {
    return *internal_default_instance();
  }
  static inline const S_PlayerLeave* internal_default_instance() {
    return reinterpret_cast<const S_PlayerLeave*>(
               &_S_PlayerLeave_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(S_PlayerLeave& a, S_PlayerLeave& b) {
    a.Swap(&b);
  }
  inline void Swap(S_PlayerLeave* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(S_PlayerLeave* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  S_PlayerLeave* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<S_PlayerLeave>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const S_PlayerLeave& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const S_PlayerLeave& from) {
    S_PlayerLeave::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(S_PlayerLeave* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.S_PlayerLeave";
  }
  protected:
  explicit S_PlayerLeave(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kObjectidFieldNumber = 1,
  };
  // uint64 objectid = 1;
  void clear_objectid();
  uint64_t objectid() const;
  void set_objectid(uint64_t value);
  private:
  uint64_t _internal_objectid() const;
  void _internal_set_objectid(uint64_t value);
  public:

  // @@protoc_insertion_point(class_scope:Protocol.S_PlayerLeave)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    uint64_t objectid_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Protocol_2eproto;
};
// -------------------------------------------------------------------

class C_Move final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.C_Move) */ {
 public:
  inline C_Move() : C_Move(nullptr) {}
  ~C_Move() override;
  explicit PROTOBUF_CONSTEXPR C_Move(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  C_Move(const C_Move& from);
  C_Move(C_Move&& from) noexcept
    : C_Move() {
    *this = ::std::move(from);
  }

  inline C_Move& operator=(const C_Move& from) {
    CopyFrom(from);
    return *this;
  }
  inline C_Move& operator=(C_Move&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const C_Move& default_instance() {
    return *internal_default_instance();
  }
  static inline const C_Move* internal_default_instance() {
    return reinterpret_cast<const C_Move*>(
               &_C_Move_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(C_Move& a, C_Move& b) {
    a.Swap(&b);
  }
  inline void Swap(C_Move* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(C_Move* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  C_Move* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<C_Move>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const C_Move& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const C_Move& from) {
    C_Move::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(C_Move* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.C_Move";
  }
  protected:
  explicit C_Move(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kObjectidFieldNumber = 1,
    kStateFieldNumber = 2,
    kDirFieldNumber = 3,
    kPosxFieldNumber = 4,
    kPosyFieldNumber = 5,
  };
  // uint64 objectid = 1;
  void clear_objectid();
  uint64_t objectid() const;
  void set_objectid(uint64_t value);
  private:
  uint64_t _internal_objectid() const;
  void _internal_set_objectid(uint64_t value);
  public:

  // uint32 state = 2;
  void clear_state();
  uint32_t state() const;
  void set_state(uint32_t value);
  private:
  uint32_t _internal_state() const;
  void _internal_set_state(uint32_t value);
  public:

  // int32 dir = 3;
  void clear_dir();
  int32_t dir() const;
  void set_dir(int32_t value);
  private:
  int32_t _internal_dir() const;
  void _internal_set_dir(int32_t value);
  public:

  // float posx = 4;
  void clear_posx();
  float posx() const;
  void set_posx(float value);
  private:
  float _internal_posx() const;
  void _internal_set_posx(float value);
  public:

  // float posy = 5;
  void clear_posy();
  float posy() const;
  void set_posy(float value);
  private:
  float _internal_posy() const;
  void _internal_set_posy(float value);
  public:

  // @@protoc_insertion_point(class_scope:Protocol.C_Move)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    uint64_t objectid_;
    uint32_t state_;
    int32_t dir_;
    float posx_;
    float posy_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Protocol_2eproto;
};
// -------------------------------------------------------------------

class S_Move final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.S_Move) */ {
 public:
  inline S_Move() : S_Move(nullptr) {}
  ~S_Move() override;
  explicit PROTOBUF_CONSTEXPR S_Move(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  S_Move(const S_Move& from);
  S_Move(S_Move&& from) noexcept
    : S_Move() {
    *this = ::std::move(from);
  }

  inline S_Move& operator=(const S_Move& from) {
    CopyFrom(from);
    return *this;
  }
  inline S_Move& operator=(S_Move&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const S_Move& default_instance() {
    return *internal_default_instance();
  }
  static inline const S_Move* internal_default_instance() {
    return reinterpret_cast<const S_Move*>(
               &_S_Move_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    5;

  friend void swap(S_Move& a, S_Move& b) {
    a.Swap(&b);
  }
  inline void Swap(S_Move* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(S_Move* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  S_Move* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<S_Move>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const S_Move& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const S_Move& from) {
    S_Move::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(S_Move* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.S_Move";
  }
  protected:
  explicit S_Move(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kObjectidFieldNumber = 1,
    kStateFieldNumber = 2,
    kDirFieldNumber = 3,
    kPosxFieldNumber = 4,
    kPosyFieldNumber = 5,
    kNeedsyncFieldNumber = 6,
  };
  // uint64 objectid = 1;
  void clear_objectid();
  uint64_t objectid() const;
  void set_objectid(uint64_t value);
  private:
  uint64_t _internal_objectid() const;
  void _internal_set_objectid(uint64_t value);
  public:

  // uint32 state = 2;
  void clear_state();
  uint32_t state() const;
  void set_state(uint32_t value);
  private:
  uint32_t _internal_state() const;
  void _internal_set_state(uint32_t value);
  public:

  // int32 dir = 3;
  void clear_dir();
  int32_t dir() const;
  void set_dir(int32_t value);
  private:
  int32_t _internal_dir() const;
  void _internal_set_dir(int32_t value);
  public:

  // float posx = 4;
  void clear_posx();
  float posx() const;
  void set_posx(float value);
  private:
  float _internal_posx() const;
  void _internal_set_posx(float value);
  public:

  // float posy = 5;
  void clear_posy();
  float posy() const;
  void set_posy(float value);
  private:
  float _internal_posy() const;
  void _internal_set_posy(float value);
  public:

  // bool needsync = 6;
  void clear_needsync();
  bool needsync() const;
  void set_needsync(bool value);
  private:
  bool _internal_needsync() const;
  void _internal_set_needsync(bool value);
  public:

  // @@protoc_insertion_point(class_scope:Protocol.S_Move)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    uint64_t objectid_;
    uint32_t state_;
    int32_t dir_;
    float posx_;
    float posy_;
    bool needsync_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Protocol_2eproto;
};
// -------------------------------------------------------------------

class S_Tilemap final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.S_Tilemap) */ {
 public:
  inline S_Tilemap() : S_Tilemap(nullptr) {}
  ~S_Tilemap() override;
  explicit PROTOBUF_CONSTEXPR S_Tilemap(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  S_Tilemap(const S_Tilemap& from);
  S_Tilemap(S_Tilemap&& from) noexcept
    : S_Tilemap() {
    *this = ::std::move(from);
  }

  inline S_Tilemap& operator=(const S_Tilemap& from) {
    CopyFrom(from);
    return *this;
  }
  inline S_Tilemap& operator=(S_Tilemap&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const S_Tilemap& default_instance() {
    return *internal_default_instance();
  }
  static inline const S_Tilemap* internal_default_instance() {
    return reinterpret_cast<const S_Tilemap*>(
               &_S_Tilemap_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    6;

  friend void swap(S_Tilemap& a, S_Tilemap& b) {
    a.Swap(&b);
  }
  inline void Swap(S_Tilemap* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(S_Tilemap* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  S_Tilemap* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<S_Tilemap>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const S_Tilemap& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const S_Tilemap& from) {
    S_Tilemap::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(S_Tilemap* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.S_Tilemap";
  }
  protected:
  explicit S_Tilemap(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kValuesFieldNumber = 3,
    kMapsizexFieldNumber = 1,
    kMapsizeyFieldNumber = 2,
  };
  // repeated int32 values = 3;
  int values_size() const;
  private:
  int _internal_values_size() const;
  public:
  void clear_values();
  private:
  int32_t _internal_values(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >&
      _internal_values() const;
  void _internal_add_values(int32_t value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >*
      _internal_mutable_values();
  public:
  int32_t values(int index) const;
  void set_values(int index, int32_t value);
  void add_values(int32_t value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >&
      values() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >*
      mutable_values();

  // int32 mapsizex = 1;
  void clear_mapsizex();
  int32_t mapsizex() const;
  void set_mapsizex(int32_t value);
  private:
  int32_t _internal_mapsizex() const;
  void _internal_set_mapsizex(int32_t value);
  public:

  // int32 mapsizey = 2;
  void clear_mapsizey();
  int32_t mapsizey() const;
  void set_mapsizey(int32_t value);
  private:
  int32_t _internal_mapsizey() const;
  void _internal_set_mapsizey(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:Protocol.S_Tilemap)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t > values_;
    mutable std::atomic<int> _values_cached_byte_size_;
    int32_t mapsizex_;
    int32_t mapsizey_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Protocol_2eproto;
};
// -------------------------------------------------------------------

class C_WaterBomb final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.C_WaterBomb) */ {
 public:
  inline C_WaterBomb() : C_WaterBomb(nullptr) {}
  ~C_WaterBomb() override;
  explicit PROTOBUF_CONSTEXPR C_WaterBomb(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  C_WaterBomb(const C_WaterBomb& from);
  C_WaterBomb(C_WaterBomb&& from) noexcept
    : C_WaterBomb() {
    *this = ::std::move(from);
  }

  inline C_WaterBomb& operator=(const C_WaterBomb& from) {
    CopyFrom(from);
    return *this;
  }
  inline C_WaterBomb& operator=(C_WaterBomb&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const C_WaterBomb& default_instance() {
    return *internal_default_instance();
  }
  static inline const C_WaterBomb* internal_default_instance() {
    return reinterpret_cast<const C_WaterBomb*>(
               &_C_WaterBomb_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    7;

  friend void swap(C_WaterBomb& a, C_WaterBomb& b) {
    a.Swap(&b);
  }
  inline void Swap(C_WaterBomb* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(C_WaterBomb* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  C_WaterBomb* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<C_WaterBomb>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const C_WaterBomb& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const C_WaterBomb& from) {
    C_WaterBomb::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(C_WaterBomb* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.C_WaterBomb";
  }
  protected:
  explicit C_WaterBomb(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kOwneridFieldNumber = 1,
    kTileposxFieldNumber = 2,
    kTileposyFieldNumber = 3,
  };
  // uint64 ownerid = 1;
  void clear_ownerid();
  uint64_t ownerid() const;
  void set_ownerid(uint64_t value);
  private:
  uint64_t _internal_ownerid() const;
  void _internal_set_ownerid(uint64_t value);
  public:

  // int32 tileposx = 2;
  void clear_tileposx();
  int32_t tileposx() const;
  void set_tileposx(int32_t value);
  private:
  int32_t _internal_tileposx() const;
  void _internal_set_tileposx(int32_t value);
  public:

  // int32 tileposy = 3;
  void clear_tileposy();
  int32_t tileposy() const;
  void set_tileposy(int32_t value);
  private:
  int32_t _internal_tileposy() const;
  void _internal_set_tileposy(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:Protocol.C_WaterBomb)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    uint64_t ownerid_;
    int32_t tileposx_;
    int32_t tileposy_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Protocol_2eproto;
};
// -------------------------------------------------------------------

class S_WaterBomb final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.S_WaterBomb) */ {
 public:
  inline S_WaterBomb() : S_WaterBomb(nullptr) {}
  ~S_WaterBomb() override;
  explicit PROTOBUF_CONSTEXPR S_WaterBomb(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  S_WaterBomb(const S_WaterBomb& from);
  S_WaterBomb(S_WaterBomb&& from) noexcept
    : S_WaterBomb() {
    *this = ::std::move(from);
  }

  inline S_WaterBomb& operator=(const S_WaterBomb& from) {
    CopyFrom(from);
    return *this;
  }
  inline S_WaterBomb& operator=(S_WaterBomb&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const S_WaterBomb& default_instance() {
    return *internal_default_instance();
  }
  static inline const S_WaterBomb* internal_default_instance() {
    return reinterpret_cast<const S_WaterBomb*>(
               &_S_WaterBomb_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    8;

  friend void swap(S_WaterBomb& a, S_WaterBomb& b) {
    a.Swap(&b);
  }
  inline void Swap(S_WaterBomb* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(S_WaterBomb* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  S_WaterBomb* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<S_WaterBomb>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const S_WaterBomb& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const S_WaterBomb& from) {
    S_WaterBomb::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(S_WaterBomb* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.S_WaterBomb";
  }
  protected:
  explicit S_WaterBomb(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kObjectidFieldNumber = 1,
    kOwneridFieldNumber = 2,
    kTileposxFieldNumber = 3,
    kTileposyFieldNumber = 4,
  };
  // uint64 objectid = 1;
  void clear_objectid();
  uint64_t objectid() const;
  void set_objectid(uint64_t value);
  private:
  uint64_t _internal_objectid() const;
  void _internal_set_objectid(uint64_t value);
  public:

  // uint64 ownerid = 2;
  void clear_ownerid();
  uint64_t ownerid() const;
  void set_ownerid(uint64_t value);
  private:
  uint64_t _internal_ownerid() const;
  void _internal_set_ownerid(uint64_t value);
  public:

  // int32 tileposx = 3;
  void clear_tileposx();
  int32_t tileposx() const;
  void set_tileposx(int32_t value);
  private:
  int32_t _internal_tileposx() const;
  void _internal_set_tileposx(int32_t value);
  public:

  // int32 tileposy = 4;
  void clear_tileposy();
  int32_t tileposy() const;
  void set_tileposy(int32_t value);
  private:
  int32_t _internal_tileposy() const;
  void _internal_set_tileposy(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:Protocol.S_WaterBomb)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    uint64_t objectid_;
    uint64_t ownerid_;
    int32_t tileposx_;
    int32_t tileposy_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Protocol_2eproto;
};
// -------------------------------------------------------------------

class S_Explode final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.S_Explode) */ {
 public:
  inline S_Explode() : S_Explode(nullptr) {}
  ~S_Explode() override;
  explicit PROTOBUF_CONSTEXPR S_Explode(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  S_Explode(const S_Explode& from);
  S_Explode(S_Explode&& from) noexcept
    : S_Explode() {
    *this = ::std::move(from);
  }

  inline S_Explode& operator=(const S_Explode& from) {
    CopyFrom(from);
    return *this;
  }
  inline S_Explode& operator=(S_Explode&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const S_Explode& default_instance() {
    return *internal_default_instance();
  }
  static inline const S_Explode* internal_default_instance() {
    return reinterpret_cast<const S_Explode*>(
               &_S_Explode_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    9;

  friend void swap(S_Explode& a, S_Explode& b) {
    a.Swap(&b);
  }
  inline void Swap(S_Explode* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(S_Explode* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  S_Explode* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<S_Explode>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const S_Explode& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const S_Explode& from) {
    S_Explode::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(S_Explode* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.S_Explode";
  }
  protected:
  explicit S_Explode(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kObjectidFieldNumber = 1,
  };
  // uint64 objectid = 1;
  void clear_objectid();
  uint64_t objectid() const;
  void set_objectid(uint64_t value);
  private:
  uint64_t _internal_objectid() const;
  void _internal_set_objectid(uint64_t value);
  public:

  // @@protoc_insertion_point(class_scope:Protocol.S_Explode)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    uint64_t objectid_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Protocol_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// S_EnterGame

// bool success = 1;
inline void S_EnterGame::clear_success() {
  _impl_.success_ = false;
}
inline bool S_EnterGame::_internal_success() const {
  return _impl_.success_;
}
inline bool S_EnterGame::success() const {
  // @@protoc_insertion_point(field_get:Protocol.S_EnterGame.success)
  return _internal_success();
}
inline void S_EnterGame::_internal_set_success(bool value) {
  
  _impl_.success_ = value;
}
inline void S_EnterGame::set_success(bool value) {
  _internal_set_success(value);
  // @@protoc_insertion_point(field_set:Protocol.S_EnterGame.success)
}

// uint64 accountId = 2;
inline void S_EnterGame::clear_accountid() {
  _impl_.accountid_ = uint64_t{0u};
}
inline uint64_t S_EnterGame::_internal_accountid() const {
  return _impl_.accountid_;
}
inline uint64_t S_EnterGame::accountid() const {
  // @@protoc_insertion_point(field_get:Protocol.S_EnterGame.accountId)
  return _internal_accountid();
}
inline void S_EnterGame::_internal_set_accountid(uint64_t value) {
  
  _impl_.accountid_ = value;
}
inline void S_EnterGame::set_accountid(uint64_t value) {
  _internal_set_accountid(value);
  // @@protoc_insertion_point(field_set:Protocol.S_EnterGame.accountId)
}

// -------------------------------------------------------------------

// S_MyPlayer

// .Protocol.PlayerInfo info = 1;
inline bool S_MyPlayer::_internal_has_info() const {
  return this != internal_default_instance() && _impl_.info_ != nullptr;
}
inline bool S_MyPlayer::has_info() const {
  return _internal_has_info();
}
inline const ::Protocol::PlayerInfo& S_MyPlayer::_internal_info() const {
  const ::Protocol::PlayerInfo* p = _impl_.info_;
  return p != nullptr ? *p : reinterpret_cast<const ::Protocol::PlayerInfo&>(
      ::Protocol::_PlayerInfo_default_instance_);
}
inline const ::Protocol::PlayerInfo& S_MyPlayer::info() const {
  // @@protoc_insertion_point(field_get:Protocol.S_MyPlayer.info)
  return _internal_info();
}
inline void S_MyPlayer::unsafe_arena_set_allocated_info(
    ::Protocol::PlayerInfo* info) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.info_);
  }
  _impl_.info_ = info;
  if (info) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:Protocol.S_MyPlayer.info)
}
inline ::Protocol::PlayerInfo* S_MyPlayer::release_info() {
  
  ::Protocol::PlayerInfo* temp = _impl_.info_;
  _impl_.info_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::Protocol::PlayerInfo* S_MyPlayer::unsafe_arena_release_info() {
  // @@protoc_insertion_point(field_release:Protocol.S_MyPlayer.info)
  
  ::Protocol::PlayerInfo* temp = _impl_.info_;
  _impl_.info_ = nullptr;
  return temp;
}
inline ::Protocol::PlayerInfo* S_MyPlayer::_internal_mutable_info() {
  
  if (_impl_.info_ == nullptr) {
    auto* p = CreateMaybeMessage<::Protocol::PlayerInfo>(GetArenaForAllocation());
    _impl_.info_ = p;
  }
  return _impl_.info_;
}
inline ::Protocol::PlayerInfo* S_MyPlayer::mutable_info() {
  ::Protocol::PlayerInfo* _msg = _internal_mutable_info();
  // @@protoc_insertion_point(field_mutable:Protocol.S_MyPlayer.info)
  return _msg;
}
inline void S_MyPlayer::set_allocated_info(::Protocol::PlayerInfo* info) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.info_);
  }
  if (info) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(info));
    if (message_arena != submessage_arena) {
      info = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, info, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.info_ = info;
  // @@protoc_insertion_point(field_set_allocated:Protocol.S_MyPlayer.info)
}

// -------------------------------------------------------------------

// S_OtherPlayers

// repeated .Protocol.PlayerInfo infos = 1;
inline int S_OtherPlayers::_internal_infos_size() const {
  return _impl_.infos_.size();
}
inline int S_OtherPlayers::infos_size() const {
  return _internal_infos_size();
}
inline ::Protocol::PlayerInfo* S_OtherPlayers::mutable_infos(int index) {
  // @@protoc_insertion_point(field_mutable:Protocol.S_OtherPlayers.infos)
  return _impl_.infos_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Protocol::PlayerInfo >*
S_OtherPlayers::mutable_infos() {
  // @@protoc_insertion_point(field_mutable_list:Protocol.S_OtherPlayers.infos)
  return &_impl_.infos_;
}
inline const ::Protocol::PlayerInfo& S_OtherPlayers::_internal_infos(int index) const {
  return _impl_.infos_.Get(index);
}
inline const ::Protocol::PlayerInfo& S_OtherPlayers::infos(int index) const {
  // @@protoc_insertion_point(field_get:Protocol.S_OtherPlayers.infos)
  return _internal_infos(index);
}
inline ::Protocol::PlayerInfo* S_OtherPlayers::_internal_add_infos() {
  return _impl_.infos_.Add();
}
inline ::Protocol::PlayerInfo* S_OtherPlayers::add_infos() {
  ::Protocol::PlayerInfo* _add = _internal_add_infos();
  // @@protoc_insertion_point(field_add:Protocol.S_OtherPlayers.infos)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Protocol::PlayerInfo >&
S_OtherPlayers::infos() const {
  // @@protoc_insertion_point(field_list:Protocol.S_OtherPlayers.infos)
  return _impl_.infos_;
}

// -------------------------------------------------------------------

// S_PlayerLeave

// uint64 objectid = 1;
inline void S_PlayerLeave::clear_objectid() {
  _impl_.objectid_ = uint64_t{0u};
}
inline uint64_t S_PlayerLeave::_internal_objectid() const {
  return _impl_.objectid_;
}
inline uint64_t S_PlayerLeave::objectid() const {
  // @@protoc_insertion_point(field_get:Protocol.S_PlayerLeave.objectid)
  return _internal_objectid();
}
inline void S_PlayerLeave::_internal_set_objectid(uint64_t value) {
  
  _impl_.objectid_ = value;
}
inline void S_PlayerLeave::set_objectid(uint64_t value) {
  _internal_set_objectid(value);
  // @@protoc_insertion_point(field_set:Protocol.S_PlayerLeave.objectid)
}

// -------------------------------------------------------------------

// C_Move

// uint64 objectid = 1;
inline void C_Move::clear_objectid() {
  _impl_.objectid_ = uint64_t{0u};
}
inline uint64_t C_Move::_internal_objectid() const {
  return _impl_.objectid_;
}
inline uint64_t C_Move::objectid() const {
  // @@protoc_insertion_point(field_get:Protocol.C_Move.objectid)
  return _internal_objectid();
}
inline void C_Move::_internal_set_objectid(uint64_t value) {
  
  _impl_.objectid_ = value;
}
inline void C_Move::set_objectid(uint64_t value) {
  _internal_set_objectid(value);
  // @@protoc_insertion_point(field_set:Protocol.C_Move.objectid)
}

// uint32 state = 2;
inline void C_Move::clear_state() {
  _impl_.state_ = 0u;
}
inline uint32_t C_Move::_internal_state() const {
  return _impl_.state_;
}
inline uint32_t C_Move::state() const {
  // @@protoc_insertion_point(field_get:Protocol.C_Move.state)
  return _internal_state();
}
inline void C_Move::_internal_set_state(uint32_t value) {
  
  _impl_.state_ = value;
}
inline void C_Move::set_state(uint32_t value) {
  _internal_set_state(value);
  // @@protoc_insertion_point(field_set:Protocol.C_Move.state)
}

// int32 dir = 3;
inline void C_Move::clear_dir() {
  _impl_.dir_ = 0;
}
inline int32_t C_Move::_internal_dir() const {
  return _impl_.dir_;
}
inline int32_t C_Move::dir() const {
  // @@protoc_insertion_point(field_get:Protocol.C_Move.dir)
  return _internal_dir();
}
inline void C_Move::_internal_set_dir(int32_t value) {
  
  _impl_.dir_ = value;
}
inline void C_Move::set_dir(int32_t value) {
  _internal_set_dir(value);
  // @@protoc_insertion_point(field_set:Protocol.C_Move.dir)
}

// float posx = 4;
inline void C_Move::clear_posx() {
  _impl_.posx_ = 0;
}
inline float C_Move::_internal_posx() const {
  return _impl_.posx_;
}
inline float C_Move::posx() const {
  // @@protoc_insertion_point(field_get:Protocol.C_Move.posx)
  return _internal_posx();
}
inline void C_Move::_internal_set_posx(float value) {
  
  _impl_.posx_ = value;
}
inline void C_Move::set_posx(float value) {
  _internal_set_posx(value);
  // @@protoc_insertion_point(field_set:Protocol.C_Move.posx)
}

// float posy = 5;
inline void C_Move::clear_posy() {
  _impl_.posy_ = 0;
}
inline float C_Move::_internal_posy() const {
  return _impl_.posy_;
}
inline float C_Move::posy() const {
  // @@protoc_insertion_point(field_get:Protocol.C_Move.posy)
  return _internal_posy();
}
inline void C_Move::_internal_set_posy(float value) {
  
  _impl_.posy_ = value;
}
inline void C_Move::set_posy(float value) {
  _internal_set_posy(value);
  // @@protoc_insertion_point(field_set:Protocol.C_Move.posy)
}

// -------------------------------------------------------------------

// S_Move

// uint64 objectid = 1;
inline void S_Move::clear_objectid() {
  _impl_.objectid_ = uint64_t{0u};
}
inline uint64_t S_Move::_internal_objectid() const {
  return _impl_.objectid_;
}
inline uint64_t S_Move::objectid() const {
  // @@protoc_insertion_point(field_get:Protocol.S_Move.objectid)
  return _internal_objectid();
}
inline void S_Move::_internal_set_objectid(uint64_t value) {
  
  _impl_.objectid_ = value;
}
inline void S_Move::set_objectid(uint64_t value) {
  _internal_set_objectid(value);
  // @@protoc_insertion_point(field_set:Protocol.S_Move.objectid)
}

// uint32 state = 2;
inline void S_Move::clear_state() {
  _impl_.state_ = 0u;
}
inline uint32_t S_Move::_internal_state() const {
  return _impl_.state_;
}
inline uint32_t S_Move::state() const {
  // @@protoc_insertion_point(field_get:Protocol.S_Move.state)
  return _internal_state();
}
inline void S_Move::_internal_set_state(uint32_t value) {
  
  _impl_.state_ = value;
}
inline void S_Move::set_state(uint32_t value) {
  _internal_set_state(value);
  // @@protoc_insertion_point(field_set:Protocol.S_Move.state)
}

// int32 dir = 3;
inline void S_Move::clear_dir() {
  _impl_.dir_ = 0;
}
inline int32_t S_Move::_internal_dir() const {
  return _impl_.dir_;
}
inline int32_t S_Move::dir() const {
  // @@protoc_insertion_point(field_get:Protocol.S_Move.dir)
  return _internal_dir();
}
inline void S_Move::_internal_set_dir(int32_t value) {
  
  _impl_.dir_ = value;
}
inline void S_Move::set_dir(int32_t value) {
  _internal_set_dir(value);
  // @@protoc_insertion_point(field_set:Protocol.S_Move.dir)
}

// float posx = 4;
inline void S_Move::clear_posx() {
  _impl_.posx_ = 0;
}
inline float S_Move::_internal_posx() const {
  return _impl_.posx_;
}
inline float S_Move::posx() const {
  // @@protoc_insertion_point(field_get:Protocol.S_Move.posx)
  return _internal_posx();
}
inline void S_Move::_internal_set_posx(float value) {
  
  _impl_.posx_ = value;
}
inline void S_Move::set_posx(float value) {
  _internal_set_posx(value);
  // @@protoc_insertion_point(field_set:Protocol.S_Move.posx)
}

// float posy = 5;
inline void S_Move::clear_posy() {
  _impl_.posy_ = 0;
}
inline float S_Move::_internal_posy() const {
  return _impl_.posy_;
}
inline float S_Move::posy() const {
  // @@protoc_insertion_point(field_get:Protocol.S_Move.posy)
  return _internal_posy();
}
inline void S_Move::_internal_set_posy(float value) {
  
  _impl_.posy_ = value;
}
inline void S_Move::set_posy(float value) {
  _internal_set_posy(value);
  // @@protoc_insertion_point(field_set:Protocol.S_Move.posy)
}

// bool needsync = 6;
inline void S_Move::clear_needsync() {
  _impl_.needsync_ = false;
}
inline bool S_Move::_internal_needsync() const {
  return _impl_.needsync_;
}
inline bool S_Move::needsync() const {
  // @@protoc_insertion_point(field_get:Protocol.S_Move.needsync)
  return _internal_needsync();
}
inline void S_Move::_internal_set_needsync(bool value) {
  
  _impl_.needsync_ = value;
}
inline void S_Move::set_needsync(bool value) {
  _internal_set_needsync(value);
  // @@protoc_insertion_point(field_set:Protocol.S_Move.needsync)
}

// -------------------------------------------------------------------

// S_Tilemap

// int32 mapsizex = 1;
inline void S_Tilemap::clear_mapsizex() {
  _impl_.mapsizex_ = 0;
}
inline int32_t S_Tilemap::_internal_mapsizex() const {
  return _impl_.mapsizex_;
}
inline int32_t S_Tilemap::mapsizex() const {
  // @@protoc_insertion_point(field_get:Protocol.S_Tilemap.mapsizex)
  return _internal_mapsizex();
}
inline void S_Tilemap::_internal_set_mapsizex(int32_t value) {
  
  _impl_.mapsizex_ = value;
}
inline void S_Tilemap::set_mapsizex(int32_t value) {
  _internal_set_mapsizex(value);
  // @@protoc_insertion_point(field_set:Protocol.S_Tilemap.mapsizex)
}

// int32 mapsizey = 2;
inline void S_Tilemap::clear_mapsizey() {
  _impl_.mapsizey_ = 0;
}
inline int32_t S_Tilemap::_internal_mapsizey() const {
  return _impl_.mapsizey_;
}
inline int32_t S_Tilemap::mapsizey() const {
  // @@protoc_insertion_point(field_get:Protocol.S_Tilemap.mapsizey)
  return _internal_mapsizey();
}
inline void S_Tilemap::_internal_set_mapsizey(int32_t value) {
  
  _impl_.mapsizey_ = value;
}
inline void S_Tilemap::set_mapsizey(int32_t value) {
  _internal_set_mapsizey(value);
  // @@protoc_insertion_point(field_set:Protocol.S_Tilemap.mapsizey)
}

// repeated int32 values = 3;
inline int S_Tilemap::_internal_values_size() const {
  return _impl_.values_.size();
}
inline int S_Tilemap::values_size() const {
  return _internal_values_size();
}
inline void S_Tilemap::clear_values() {
  _impl_.values_.Clear();
}
inline int32_t S_Tilemap::_internal_values(int index) const {
  return _impl_.values_.Get(index);
}
inline int32_t S_Tilemap::values(int index) const {
  // @@protoc_insertion_point(field_get:Protocol.S_Tilemap.values)
  return _internal_values(index);
}
inline void S_Tilemap::set_values(int index, int32_t value) {
  _impl_.values_.Set(index, value);
  // @@protoc_insertion_point(field_set:Protocol.S_Tilemap.values)
}
inline void S_Tilemap::_internal_add_values(int32_t value) {
  _impl_.values_.Add(value);
}
inline void S_Tilemap::add_values(int32_t value) {
  _internal_add_values(value);
  // @@protoc_insertion_point(field_add:Protocol.S_Tilemap.values)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >&
S_Tilemap::_internal_values() const {
  return _impl_.values_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >&
S_Tilemap::values() const {
  // @@protoc_insertion_point(field_list:Protocol.S_Tilemap.values)
  return _internal_values();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >*
S_Tilemap::_internal_mutable_values() {
  return &_impl_.values_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >*
S_Tilemap::mutable_values() {
  // @@protoc_insertion_point(field_mutable_list:Protocol.S_Tilemap.values)
  return _internal_mutable_values();
}

// -------------------------------------------------------------------

// C_WaterBomb

// uint64 ownerid = 1;
inline void C_WaterBomb::clear_ownerid() {
  _impl_.ownerid_ = uint64_t{0u};
}
inline uint64_t C_WaterBomb::_internal_ownerid() const {
  return _impl_.ownerid_;
}
inline uint64_t C_WaterBomb::ownerid() const {
  // @@protoc_insertion_point(field_get:Protocol.C_WaterBomb.ownerid)
  return _internal_ownerid();
}
inline void C_WaterBomb::_internal_set_ownerid(uint64_t value) {
  
  _impl_.ownerid_ = value;
}
inline void C_WaterBomb::set_ownerid(uint64_t value) {
  _internal_set_ownerid(value);
  // @@protoc_insertion_point(field_set:Protocol.C_WaterBomb.ownerid)
}

// int32 tileposx = 2;
inline void C_WaterBomb::clear_tileposx() {
  _impl_.tileposx_ = 0;
}
inline int32_t C_WaterBomb::_internal_tileposx() const {
  return _impl_.tileposx_;
}
inline int32_t C_WaterBomb::tileposx() const {
  // @@protoc_insertion_point(field_get:Protocol.C_WaterBomb.tileposx)
  return _internal_tileposx();
}
inline void C_WaterBomb::_internal_set_tileposx(int32_t value) {
  
  _impl_.tileposx_ = value;
}
inline void C_WaterBomb::set_tileposx(int32_t value) {
  _internal_set_tileposx(value);
  // @@protoc_insertion_point(field_set:Protocol.C_WaterBomb.tileposx)
}

// int32 tileposy = 3;
inline void C_WaterBomb::clear_tileposy() {
  _impl_.tileposy_ = 0;
}
inline int32_t C_WaterBomb::_internal_tileposy() const {
  return _impl_.tileposy_;
}
inline int32_t C_WaterBomb::tileposy() const {
  // @@protoc_insertion_point(field_get:Protocol.C_WaterBomb.tileposy)
  return _internal_tileposy();
}
inline void C_WaterBomb::_internal_set_tileposy(int32_t value) {
  
  _impl_.tileposy_ = value;
}
inline void C_WaterBomb::set_tileposy(int32_t value) {
  _internal_set_tileposy(value);
  // @@protoc_insertion_point(field_set:Protocol.C_WaterBomb.tileposy)
}

// -------------------------------------------------------------------

// S_WaterBomb

// uint64 objectid = 1;
inline void S_WaterBomb::clear_objectid() {
  _impl_.objectid_ = uint64_t{0u};
}
inline uint64_t S_WaterBomb::_internal_objectid() const {
  return _impl_.objectid_;
}
inline uint64_t S_WaterBomb::objectid() const {
  // @@protoc_insertion_point(field_get:Protocol.S_WaterBomb.objectid)
  return _internal_objectid();
}
inline void S_WaterBomb::_internal_set_objectid(uint64_t value) {
  
  _impl_.objectid_ = value;
}
inline void S_WaterBomb::set_objectid(uint64_t value) {
  _internal_set_objectid(value);
  // @@protoc_insertion_point(field_set:Protocol.S_WaterBomb.objectid)
}

// uint64 ownerid = 2;
inline void S_WaterBomb::clear_ownerid() {
  _impl_.ownerid_ = uint64_t{0u};
}
inline uint64_t S_WaterBomb::_internal_ownerid() const {
  return _impl_.ownerid_;
}
inline uint64_t S_WaterBomb::ownerid() const {
  // @@protoc_insertion_point(field_get:Protocol.S_WaterBomb.ownerid)
  return _internal_ownerid();
}
inline void S_WaterBomb::_internal_set_ownerid(uint64_t value) {
  
  _impl_.ownerid_ = value;
}
inline void S_WaterBomb::set_ownerid(uint64_t value) {
  _internal_set_ownerid(value);
  // @@protoc_insertion_point(field_set:Protocol.S_WaterBomb.ownerid)
}

// int32 tileposx = 3;
inline void S_WaterBomb::clear_tileposx() {
  _impl_.tileposx_ = 0;
}
inline int32_t S_WaterBomb::_internal_tileposx() const {
  return _impl_.tileposx_;
}
inline int32_t S_WaterBomb::tileposx() const {
  // @@protoc_insertion_point(field_get:Protocol.S_WaterBomb.tileposx)
  return _internal_tileposx();
}
inline void S_WaterBomb::_internal_set_tileposx(int32_t value) {
  
  _impl_.tileposx_ = value;
}
inline void S_WaterBomb::set_tileposx(int32_t value) {
  _internal_set_tileposx(value);
  // @@protoc_insertion_point(field_set:Protocol.S_WaterBomb.tileposx)
}

// int32 tileposy = 4;
inline void S_WaterBomb::clear_tileposy() {
  _impl_.tileposy_ = 0;
}
inline int32_t S_WaterBomb::_internal_tileposy() const {
  return _impl_.tileposy_;
}
inline int32_t S_WaterBomb::tileposy() const {
  // @@protoc_insertion_point(field_get:Protocol.S_WaterBomb.tileposy)
  return _internal_tileposy();
}
inline void S_WaterBomb::_internal_set_tileposy(int32_t value) {
  
  _impl_.tileposy_ = value;
}
inline void S_WaterBomb::set_tileposy(int32_t value) {
  _internal_set_tileposy(value);
  // @@protoc_insertion_point(field_set:Protocol.S_WaterBomb.tileposy)
}

// -------------------------------------------------------------------

// S_Explode

// uint64 objectid = 1;
inline void S_Explode::clear_objectid() {
  _impl_.objectid_ = uint64_t{0u};
}
inline uint64_t S_Explode::_internal_objectid() const {
  return _impl_.objectid_;
}
inline uint64_t S_Explode::objectid() const {
  // @@protoc_insertion_point(field_get:Protocol.S_Explode.objectid)
  return _internal_objectid();
}
inline void S_Explode::_internal_set_objectid(uint64_t value) {
  
  _impl_.objectid_ = value;
}
inline void S_Explode::set_objectid(uint64_t value) {
  _internal_set_objectid(value);
  // @@protoc_insertion_point(field_set:Protocol.S_Explode.objectid)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace Protocol

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_Protocol_2eproto
