// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Struct.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_Struct_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_Struct_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_Struct_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_Struct_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_Struct_2eproto;
namespace Protocol {
class DestroyedBlockInfo;
struct DestroyedBlockInfoDefaultTypeInternal;
extern DestroyedBlockInfoDefaultTypeInternal _DestroyedBlockInfo_default_instance_;
class PlayerInfo;
struct PlayerInfoDefaultTypeInternal;
extern PlayerInfoDefaultTypeInternal _PlayerInfo_default_instance_;
class TileInfo;
struct TileInfoDefaultTypeInternal;
extern TileInfoDefaultTypeInternal _TileInfo_default_instance_;
}  // namespace Protocol
PROTOBUF_NAMESPACE_OPEN
template<> ::Protocol::DestroyedBlockInfo* Arena::CreateMaybeMessage<::Protocol::DestroyedBlockInfo>(Arena*);
template<> ::Protocol::PlayerInfo* Arena::CreateMaybeMessage<::Protocol::PlayerInfo>(Arena*);
template<> ::Protocol::TileInfo* Arena::CreateMaybeMessage<::Protocol::TileInfo>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace Protocol {

// ===================================================================

class PlayerInfo final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.PlayerInfo) */ {
 public:
  inline PlayerInfo() : PlayerInfo(nullptr) {}
  ~PlayerInfo() override;
  explicit PROTOBUF_CONSTEXPR PlayerInfo(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  PlayerInfo(const PlayerInfo& from);
  PlayerInfo(PlayerInfo&& from) noexcept
    : PlayerInfo() {
    *this = ::std::move(from);
  }

  inline PlayerInfo& operator=(const PlayerInfo& from) {
    CopyFrom(from);
    return *this;
  }
  inline PlayerInfo& operator=(PlayerInfo&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const PlayerInfo& default_instance() {
    return *internal_default_instance();
  }
  static inline const PlayerInfo* internal_default_instance() {
    return reinterpret_cast<const PlayerInfo*>(
               &_PlayerInfo_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(PlayerInfo& a, PlayerInfo& b) {
    a.Swap(&b);
  }
  inline void Swap(PlayerInfo* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PlayerInfo* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  PlayerInfo* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<PlayerInfo>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const PlayerInfo& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const PlayerInfo& from) {
    PlayerInfo::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PlayerInfo* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.PlayerInfo";
  }
  protected:
  explicit PlayerInfo(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kObjectidFieldNumber = 1,
    kPosxFieldNumber = 2,
    kPosyFieldNumber = 3,
    kMainstateFieldNumber = 4,
    kDirFieldNumber = 5,
  };
  // uint64 objectid = 1;
  void clear_objectid();
  uint64_t objectid() const;
  void set_objectid(uint64_t value);
  private:
  uint64_t _internal_objectid() const;
  void _internal_set_objectid(uint64_t value);
  public:

  // float posx = 2;
  void clear_posx();
  float posx() const;
  void set_posx(float value);
  private:
  float _internal_posx() const;
  void _internal_set_posx(float value);
  public:

  // float posy = 3;
  void clear_posy();
  float posy() const;
  void set_posy(float value);
  private:
  float _internal_posy() const;
  void _internal_set_posy(float value);
  public:

  // int32 mainstate = 4;
  void clear_mainstate();
  int32_t mainstate() const;
  void set_mainstate(int32_t value);
  private:
  int32_t _internal_mainstate() const;
  void _internal_set_mainstate(int32_t value);
  public:

  // int32 dir = 5;
  void clear_dir();
  int32_t dir() const;
  void set_dir(int32_t value);
  private:
  int32_t _internal_dir() const;
  void _internal_set_dir(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:Protocol.PlayerInfo)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    uint64_t objectid_;
    float posx_;
    float posy_;
    int32_t mainstate_;
    int32_t dir_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Struct_2eproto;
};
// -------------------------------------------------------------------

class TileInfo final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.TileInfo) */ {
 public:
  inline TileInfo() : TileInfo(nullptr) {}
  ~TileInfo() override;
  explicit PROTOBUF_CONSTEXPR TileInfo(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  TileInfo(const TileInfo& from);
  TileInfo(TileInfo&& from) noexcept
    : TileInfo() {
    *this = ::std::move(from);
  }

  inline TileInfo& operator=(const TileInfo& from) {
    CopyFrom(from);
    return *this;
  }
  inline TileInfo& operator=(TileInfo&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const TileInfo& default_instance() {
    return *internal_default_instance();
  }
  static inline const TileInfo* internal_default_instance() {
    return reinterpret_cast<const TileInfo*>(
               &_TileInfo_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(TileInfo& a, TileInfo& b) {
    a.Swap(&b);
  }
  inline void Swap(TileInfo* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(TileInfo* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  TileInfo* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<TileInfo>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const TileInfo& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const TileInfo& from) {
    TileInfo::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(TileInfo* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.TileInfo";
  }
  protected:
  explicit TileInfo(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kObjectidFieldNumber = 1,
    kMapobjecttypeFieldNumber = 2,
    kDetailedtypeFieldNumber = 3,
  };
  // uint64 objectid = 1;
  void clear_objectid();
  uint64_t objectid() const;
  void set_objectid(uint64_t value);
  private:
  uint64_t _internal_objectid() const;
  void _internal_set_objectid(uint64_t value);
  public:

  // int32 mapobjecttype = 2;
  void clear_mapobjecttype();
  int32_t mapobjecttype() const;
  void set_mapobjecttype(int32_t value);
  private:
  int32_t _internal_mapobjecttype() const;
  void _internal_set_mapobjecttype(int32_t value);
  public:

  // int32 detailedtype = 3;
  void clear_detailedtype();
  int32_t detailedtype() const;
  void set_detailedtype(int32_t value);
  private:
  int32_t _internal_detailedtype() const;
  void _internal_set_detailedtype(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:Protocol.TileInfo)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    uint64_t objectid_;
    int32_t mapobjecttype_;
    int32_t detailedtype_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Struct_2eproto;
};
// -------------------------------------------------------------------

class DestroyedBlockInfo final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.DestroyedBlockInfo) */ {
 public:
  inline DestroyedBlockInfo() : DestroyedBlockInfo(nullptr) {}
  ~DestroyedBlockInfo() override;
  explicit PROTOBUF_CONSTEXPR DestroyedBlockInfo(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  DestroyedBlockInfo(const DestroyedBlockInfo& from);
  DestroyedBlockInfo(DestroyedBlockInfo&& from) noexcept
    : DestroyedBlockInfo() {
    *this = ::std::move(from);
  }

  inline DestroyedBlockInfo& operator=(const DestroyedBlockInfo& from) {
    CopyFrom(from);
    return *this;
  }
  inline DestroyedBlockInfo& operator=(DestroyedBlockInfo&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const DestroyedBlockInfo& default_instance() {
    return *internal_default_instance();
  }
  static inline const DestroyedBlockInfo* internal_default_instance() {
    return reinterpret_cast<const DestroyedBlockInfo*>(
               &_DestroyedBlockInfo_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(DestroyedBlockInfo& a, DestroyedBlockInfo& b) {
    a.Swap(&b);
  }
  inline void Swap(DestroyedBlockInfo* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(DestroyedBlockInfo* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  DestroyedBlockInfo* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<DestroyedBlockInfo>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const DestroyedBlockInfo& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const DestroyedBlockInfo& from) {
    DestroyedBlockInfo::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(DestroyedBlockInfo* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.DestroyedBlockInfo";
  }
  protected:
  explicit DestroyedBlockInfo(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kBlockidFieldNumber = 1,
    kItemidFieldNumber = 2,
  };
  // uint64 blockid = 1;
  void clear_blockid();
  uint64_t blockid() const;
  void set_blockid(uint64_t value);
  private:
  uint64_t _internal_blockid() const;
  void _internal_set_blockid(uint64_t value);
  public:

  // uint64 itemid = 2;
  void clear_itemid();
  uint64_t itemid() const;
  void set_itemid(uint64_t value);
  private:
  uint64_t _internal_itemid() const;
  void _internal_set_itemid(uint64_t value);
  public:

  // @@protoc_insertion_point(class_scope:Protocol.DestroyedBlockInfo)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    uint64_t blockid_;
    uint64_t itemid_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Struct_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// PlayerInfo

// uint64 objectid = 1;
inline void PlayerInfo::clear_objectid() {
  _impl_.objectid_ = uint64_t{0u};
}
inline uint64_t PlayerInfo::_internal_objectid() const {
  return _impl_.objectid_;
}
inline uint64_t PlayerInfo::objectid() const {
  // @@protoc_insertion_point(field_get:Protocol.PlayerInfo.objectid)
  return _internal_objectid();
}
inline void PlayerInfo::_internal_set_objectid(uint64_t value) {
  
  _impl_.objectid_ = value;
}
inline void PlayerInfo::set_objectid(uint64_t value) {
  _internal_set_objectid(value);
  // @@protoc_insertion_point(field_set:Protocol.PlayerInfo.objectid)
}

// float posx = 2;
inline void PlayerInfo::clear_posx() {
  _impl_.posx_ = 0;
}
inline float PlayerInfo::_internal_posx() const {
  return _impl_.posx_;
}
inline float PlayerInfo::posx() const {
  // @@protoc_insertion_point(field_get:Protocol.PlayerInfo.posx)
  return _internal_posx();
}
inline void PlayerInfo::_internal_set_posx(float value) {
  
  _impl_.posx_ = value;
}
inline void PlayerInfo::set_posx(float value) {
  _internal_set_posx(value);
  // @@protoc_insertion_point(field_set:Protocol.PlayerInfo.posx)
}

// float posy = 3;
inline void PlayerInfo::clear_posy() {
  _impl_.posy_ = 0;
}
inline float PlayerInfo::_internal_posy() const {
  return _impl_.posy_;
}
inline float PlayerInfo::posy() const {
  // @@protoc_insertion_point(field_get:Protocol.PlayerInfo.posy)
  return _internal_posy();
}
inline void PlayerInfo::_internal_set_posy(float value) {
  
  _impl_.posy_ = value;
}
inline void PlayerInfo::set_posy(float value) {
  _internal_set_posy(value);
  // @@protoc_insertion_point(field_set:Protocol.PlayerInfo.posy)
}

// int32 mainstate = 4;
inline void PlayerInfo::clear_mainstate() {
  _impl_.mainstate_ = 0;
}
inline int32_t PlayerInfo::_internal_mainstate() const {
  return _impl_.mainstate_;
}
inline int32_t PlayerInfo::mainstate() const {
  // @@protoc_insertion_point(field_get:Protocol.PlayerInfo.mainstate)
  return _internal_mainstate();
}
inline void PlayerInfo::_internal_set_mainstate(int32_t value) {
  
  _impl_.mainstate_ = value;
}
inline void PlayerInfo::set_mainstate(int32_t value) {
  _internal_set_mainstate(value);
  // @@protoc_insertion_point(field_set:Protocol.PlayerInfo.mainstate)
}

// int32 dir = 5;
inline void PlayerInfo::clear_dir() {
  _impl_.dir_ = 0;
}
inline int32_t PlayerInfo::_internal_dir() const {
  return _impl_.dir_;
}
inline int32_t PlayerInfo::dir() const {
  // @@protoc_insertion_point(field_get:Protocol.PlayerInfo.dir)
  return _internal_dir();
}
inline void PlayerInfo::_internal_set_dir(int32_t value) {
  
  _impl_.dir_ = value;
}
inline void PlayerInfo::set_dir(int32_t value) {
  _internal_set_dir(value);
  // @@protoc_insertion_point(field_set:Protocol.PlayerInfo.dir)
}

// -------------------------------------------------------------------

// TileInfo

// uint64 objectid = 1;
inline void TileInfo::clear_objectid() {
  _impl_.objectid_ = uint64_t{0u};
}
inline uint64_t TileInfo::_internal_objectid() const {
  return _impl_.objectid_;
}
inline uint64_t TileInfo::objectid() const {
  // @@protoc_insertion_point(field_get:Protocol.TileInfo.objectid)
  return _internal_objectid();
}
inline void TileInfo::_internal_set_objectid(uint64_t value) {
  
  _impl_.objectid_ = value;
}
inline void TileInfo::set_objectid(uint64_t value) {
  _internal_set_objectid(value);
  // @@protoc_insertion_point(field_set:Protocol.TileInfo.objectid)
}

// int32 mapobjecttype = 2;
inline void TileInfo::clear_mapobjecttype() {
  _impl_.mapobjecttype_ = 0;
}
inline int32_t TileInfo::_internal_mapobjecttype() const {
  return _impl_.mapobjecttype_;
}
inline int32_t TileInfo::mapobjecttype() const {
  // @@protoc_insertion_point(field_get:Protocol.TileInfo.mapobjecttype)
  return _internal_mapobjecttype();
}
inline void TileInfo::_internal_set_mapobjecttype(int32_t value) {
  
  _impl_.mapobjecttype_ = value;
}
inline void TileInfo::set_mapobjecttype(int32_t value) {
  _internal_set_mapobjecttype(value);
  // @@protoc_insertion_point(field_set:Protocol.TileInfo.mapobjecttype)
}

// int32 detailedtype = 3;
inline void TileInfo::clear_detailedtype() {
  _impl_.detailedtype_ = 0;
}
inline int32_t TileInfo::_internal_detailedtype() const {
  return _impl_.detailedtype_;
}
inline int32_t TileInfo::detailedtype() const {
  // @@protoc_insertion_point(field_get:Protocol.TileInfo.detailedtype)
  return _internal_detailedtype();
}
inline void TileInfo::_internal_set_detailedtype(int32_t value) {
  
  _impl_.detailedtype_ = value;
}
inline void TileInfo::set_detailedtype(int32_t value) {
  _internal_set_detailedtype(value);
  // @@protoc_insertion_point(field_set:Protocol.TileInfo.detailedtype)
}

// -------------------------------------------------------------------

// DestroyedBlockInfo

// uint64 blockid = 1;
inline void DestroyedBlockInfo::clear_blockid() {
  _impl_.blockid_ = uint64_t{0u};
}
inline uint64_t DestroyedBlockInfo::_internal_blockid() const {
  return _impl_.blockid_;
}
inline uint64_t DestroyedBlockInfo::blockid() const {
  // @@protoc_insertion_point(field_get:Protocol.DestroyedBlockInfo.blockid)
  return _internal_blockid();
}
inline void DestroyedBlockInfo::_internal_set_blockid(uint64_t value) {
  
  _impl_.blockid_ = value;
}
inline void DestroyedBlockInfo::set_blockid(uint64_t value) {
  _internal_set_blockid(value);
  // @@protoc_insertion_point(field_set:Protocol.DestroyedBlockInfo.blockid)
}

// uint64 itemid = 2;
inline void DestroyedBlockInfo::clear_itemid() {
  _impl_.itemid_ = uint64_t{0u};
}
inline uint64_t DestroyedBlockInfo::_internal_itemid() const {
  return _impl_.itemid_;
}
inline uint64_t DestroyedBlockInfo::itemid() const {
  // @@protoc_insertion_point(field_get:Protocol.DestroyedBlockInfo.itemid)
  return _internal_itemid();
}
inline void DestroyedBlockInfo::_internal_set_itemid(uint64_t value) {
  
  _impl_.itemid_ = value;
}
inline void DestroyedBlockInfo::set_itemid(uint64_t value) {
  _internal_set_itemid(value);
  // @@protoc_insertion_point(field_set:Protocol.DestroyedBlockInfo.itemid)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace Protocol

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_Struct_2eproto
